// Copyright (c) 2002-present, OpenMS Inc. -- EKU Tuebingen, ETH Zurich, and FU Berlin
// SPDX-License-Identifier: BSD-3-Clause
// $Maintainer: OpenMS Rust contributors $

//! Filesystem entry points for the represented mzML loading and writing APIs.

use super::{LoadOptions, MSExperiment, ReadOptions, Result, WriteOptions};
use std::path::Path;

/// Load a plain, gzip or bzip2 file by content magic, independent of its suffix.
/// Uses source-default scientific loading, including stable point sorting.
/// The older stream `read` API retains its existing input-order behavior.
pub fn load(path: impl AsRef<Path>) -> Result<MSExperiment> {
    load_with_options(path, &LoadOptions::default(), &ReadOptions::default())
}

/// Read with explicit scientific settings and independent XML/binary limits.
/// Input limits count decompressed XML bytes. Successful loads record document path
/// and bounded content-detected type; stream readers leave provenance unset.
pub fn load_with_options(
    path: impl AsRef<Path>,
    scientific: &LoadOptions,
    limits: &ReadOptions,
) -> Result<MSExperiment> {
    let path = path.as_ref();
    let mut document = crate::metadata::DocumentIdentifier::new();
    let text = path
        .to_str()
        .ok_or_else(|| crate::Error::InvalidValue("mzML filename is not UTF-8".into()))?;
    document.set_loaded_file_path(text)?;
    document.set_loaded_file_type(path)?;
    let mut result =
        super::read_with_load_options(crate::format::path_io::open(path)?, scientific, limits)?;
    result.settings.document.loaded_file_path = document.loaded_file_path;
    result.settings.document.loaded_file_type = document.loaded_file_type;
    Ok(result)
}

/// Replace the destination only after successful parsing and validation.
pub fn load_into(path: impl AsRef<Path>, destination: &mut MSExperiment) -> Result<()> {
    load_into_with_options(
        path,
        destination,
        &LoadOptions::default(),
        &ReadOptions::default(),
    )
}

/// Checked whole-experiment replacement with explicit loading settings.
pub fn load_into_with_options(
    path: impl AsRef<Path>,
    destination: &mut MSExperiment,
    scientific: &LoadOptions,
    limits: &ReadOptions,
) -> Result<()> {
    let loaded = load_with_options(path, scientific, limits)?;
    *destination = loaded;
    Ok(())
}

/// Atomically store the represented mzML subset. `.gz` and `.bz2` suffixes
/// select outer compression; unknown suffixes are allowed as in XMLFile::save_.
pub fn store(path: impl AsRef<Path>, experiment: &MSExperiment) -> Result<()> {
    store_with_options(path, experiment, &WriteOptions::default())
}

/// Binary-array zlib compression is independent of filename-selected outer
/// compression. Serialization or I/O errors preserve the existing destination.
/// ZIP output is unsupported; no index is generated by this writer.
pub fn store_with_options(
    path: impl AsRef<Path>,
    experiment: &MSExperiment,
    options: &WriteOptions,
) -> Result<()> {
    crate::format::path_io::write(path.as_ref(), |writer| {
        super::write_with_options(writer, experiment, options)
    })
}
