// Copyright (c) 2002-present, OpenMS Inc. -- EKU Tuebingen, ETH Zurich, and FU Berlin
// SPDX-License-Identifier: BSD-3-Clause
// $Maintainer: OpenMS Rust contributors $

//! `FEATUREFINDER/GaussTraceFitter` against its class test and the executed
//! product-SDK libOpenMS.
//!
//! Every `START_SECTION` of `GaussTraceFitter_test.cpp` (core bc9cc12) is
//! transcribed with its literals and its comparison macros. The file sets
//! `TOLERANCE_RELATIVE(1.001)` before the first section, so `TEST_REAL_SIMILAR`
//! is ClassTest's `isRealSimilar` with ratio 1.001 and the default absolute
//! tolerance 1e-5. The source test fits once before the sections and changes the
//! theoretical intensities inside the `fit` section; each test here rebuilds that
//! state in the same order.
//!
//! The oracle replays read `tests/data/gauss_trace_fitter/`, generated by
//! `../oracle/gauss-trace-fitter/run.sh` from the C2 class-level oracle
//! (`../oracle/featurefinder-picked`) and from its own driver. Library values
//! (start values, functor residuals and Jacobians, fitted parameters and every
//! query) are oracle-generated, tier 1; the Levenberg-Marquardt status, `nfev`,
//! `njev` and evaluation path come from C2's adapted `optimize_` replica, which
//! C2 checked against the library at every budget.
//!
//! Each fit is checked in two parts. The fitted parameters are compared within
//! 1e-9 relative, the work package's tolerance. The queries (bounds, FWHM, area,
//! values, span checks, `computeTheoretical`, gnuplot formulas) are then
//! evaluated on the oracle's own fitted parameters, so that they check the
//! query arithmetic and not the fit a second time, and are compared within
//! 1e-14 relative, as the start values, residuals and Jacobians are. Integers,
//! booleans, strings and the budget boundaries are compared exactly. The oracle
//! ran on macOS arm64 with Apple libm and Eigen 5.0.1; the port calls the
//! platform `exp` and `log` and the Eigen transcription in
//! `openms::math::fitters::levenberg_marquardt`. The platform `exp` differs in
//! the last bit between glibc and Apple libm, so the bit-identical counts and
//! some fit deviations differ between Linux and macOS; every tolerance holds on
//! both (`docs/TRACE_FITTER_SUPPORT.md`, native difference 1). Each replay
//! prints how many values were bit-identical and the largest relative
//! deviation it met.
//!
//! The fit, status, `nfev` and `njev` agreement of these replays holds for
//! these fixtures only. On other inputs the Eigen transcription departs from
//! the executed solver in the last bits, usually at the first trial step, and
//! fits can miss 1e-9 by orders of magnitude. The review probe's 79 inputs
//! (`tests/data/gauss_trace_fitter/solver_gap.tsv`, from
//! `../oracle/gauss-trace-fitter/solver-gap`) record that gap. Their start
//! values, and the residuals and Jacobians at them, are asserted; the ignored
//! `solver_gap_probe_reports_the_known_gap` prints the rest without asserting
//! any Rust value.
//!
//! That root cause was found and fixed in `src/math/fitters/levenberg_marquardt.rs`
//! by package B3b-LM-FIDELITY: the transcription summed left to right where
//! Eigen accumulates in SIMD lanes. What is left against these fixtures is the
//! platform split Eigen itself has - its arm64 kernels fuse their `pmadd` lanes
//! and its x86_64 `-mssse3` kernels do not - and the user decided on 2026-09-15
//! that the port matches the **Linux x86_64 Release** build on every target,
//! while these fixtures come from the macOS arm64 product SDK. See
//! `docs/DISTRIBUTION_FITTERS_SUPPORT.md` §1 and, for the asserted replay
//! against a Linux x86_64 Release trace of Eigen,
//! `tests/lm_eigen_path_differential.rs`.

// The class-test literals are transcribed verbatim, including digits beyond
// the precision of their type, so the f32 values match the C++ literals exactly.
#![allow(clippy::excessive_precision)]

use std::cell::{Cell, RefCell};
use std::collections::BTreeMap;

use openms::Error;
use openms::analysis::feature_finder_picked::gauss_trace_fitter::{
    GaussTraceFitter, GaussTraceFunctor,
};
use openms::analysis::feature_finder_picked::helper_structs::{MassTrace, MassTraces, TracePeak};
use openms::analysis::feature_finder_picked::trace_fitter::{
    TraceFitter, TraceFitterParams, optimize_with_status,
};
use openms::math::fitters::levenberg_marquardt::{DenseMatrix, LmStatus};
use openms::param::{Param, ParamValue};

const CLASSTEST: &str = include_str!("data/gauss_trace_fitter/classtest.tsv");
const DEGENERATE: &str = include_str!("data/gauss_trace_fitter/degenerate.tsv");
const FFC1_SEEDS: &str = include_str!("data/gauss_trace_fitter/ffc1_seeds.tsv");
const EXTRA: &str = include_str!("data/gauss_trace_fitter/gauss_extra.tsv");

/// Relative tolerance for start values, residuals, Jacobians and queries.
const EXACT_TOLERANCE: f64 = 1e-14;
/// Relative tolerance for fitted parameters and evaluation paths.
const FIT_TOLERANCE: f64 = 1e-9;

// ---------------------------------------------------------------------------
// The class test's input (GaussTraceFitter_test.cpp:26-216)
// ---------------------------------------------------------------------------

const CT_RT: [f64; 21] = [
    677.1, 677.4, 677.7, 678.0, 678.3, 678.6, 678.9, 679.2, 679.5, 679.8, 680.1, 680.4, 680.7,
    681.0, 681.3, 681.6, 681.9, 682.2, 682.5, 682.8, 683.1,
];
const CT_I1: [f32; 21] = [
    1.08268226589,
    1.58318959267,
    2.22429840363,
    3.00248879081,
    3.89401804768,
    4.8522452777,
    5.80919229659,
    6.68216169129,
    7.38493077109,
    7.84158938645,
    8.0,
    7.84158938645,
    7.38493077109,
    6.68216169129,
    5.80919229659,
    4.8522452777,
    3.89401804768,
    3.00248879081,
    2.22429840363,
    1.58318959267,
    1.08268226589,
];
const CT_I2: [f32; 21] = [
    0.270670566473,
    0.395797398167,
    0.556074600906,
    0.750622197703,
    0.97350451192,
    1.21306131943,
    1.45229807415,
    1.67054042282,
    1.84623269277,
    1.96039734661,
    2.0,
    1.96039734661,
    1.84623269277,
    1.67054042282,
    1.45229807415,
    1.21306131943,
    0.97350451192,
    0.750622197703,
    0.556074600906,
    0.395797398167,
    0.270670566473,
];

fn class_test_trace(theoretical_int: f64, intensities: &[f32; 21], mz: f64) -> MassTrace {
    let mut trace = MassTrace {
        theoretical_int,
        ..MassTrace::default()
    };
    for (k, (&rt, &intensity)) in CT_RT.iter().zip(intensities).enumerate() {
        trace.peaks.push(TracePeak::new(0, k, rt, mz, intensity));
    }
    trace.update_maximum();
    trace
}

/// `mts` of the class test with the given theoretical intensities, baseline 0
/// and `max_trace` 0.
fn class_test_traces(theo1: f64, theo2: f64) -> MassTraces {
    let mut traces = MassTraces::new();
    traces.push(class_test_trace(theo1, &CT_I1, 1000.0));
    traces.push(class_test_trace(theo2, &CT_I2, 1001.0));
    traces.baseline = 0.0;
    traces.max_trace = 0;
    traces
}

// ---------------------------------------------------------------------------
// ClassTest comparison
// ---------------------------------------------------------------------------

/// ClassTest `isRealSimilar` (ClassTest.cpp:364-470) with
/// `TOLERANCE_RELATIVE(1.001)` and the default `absdiff_max_allowed` 1e-5. The
/// source evaluates in `long double`; the transcribed cases are far from both
/// limits.
fn is_real_similar(number_1: f64, number_2: f64) -> bool {
    const ABSDIFF_MAX_ALLOWED: f64 = 1e-5;
    const RATIO_MAX_ALLOWED: f64 = 1.001;
    if number_1.is_nan() || number_2.is_nan() {
        return false;
    }
    let is_absdiff_small = (number_1 - number_2).abs() <= ABSDIFF_MAX_ALLOWED;
    if number_1 == 0.0 || number_2 == 0.0 {
        return (number_1 == 0.0 && number_2 == 0.0) || is_absdiff_small;
    }
    let mut ratio = number_1 / number_2;
    if ratio < 0.0 {
        return is_absdiff_small;
    }
    if ratio < 1.0 {
        ratio = 1.0 / ratio;
    }
    ratio <= RATIO_MAX_ALLOWED || is_absdiff_small
}

#[track_caller]
fn test_real_similar(actual: f64, expected: f64) {
    assert!(
        is_real_similar(actual, expected),
        "TEST_REAL_SIMILAR({actual}, {expected}) failed"
    );
}

/// The class test's fitter: `Param p; p.setValue("max_iteration", 500);`,
/// `setParameters(p)`, `fit(mts)`.
fn class_test_fitter(traces: &MassTraces) -> GaussTraceFitter {
    let mut param = Param::new();
    param
        .set_value("max_iteration", ParamValue::Integer(500), "", &[])
        .unwrap();
    let (parameters, warnings) = TraceFitterParams::from_param(&param).unwrap();
    assert!(warnings.is_empty(), "{warnings:?}");
    let mut fitter = GaussTraceFitter::new();
    fitter.set_parameters(parameters);
    fitter.fit(traces).unwrap();
    fitter
}

const EXPECTED_SIGMA: f64 = 1.5;
const EXPECTED_H: f64 = 10.0;
const EXPECTED_X0: f64 = 680.1;

// ---------------------------------------------------------------------------
// START_SECTIONs of GaussTraceFitter_test.cpp
// ---------------------------------------------------------------------------

/// `START_SECTION(GaussTraceFitter())` and `START_SECTION(~GaussTraceFitter())`.
#[test]
fn section_constructor_and_destructor() {
    let fitter = Box::new(GaussTraceFitter::new());
    assert_eq!(*fitter.parameters(), TraceFitterParams::default());
    drop(fitter);
}

/// `START_SECTION((GaussTraceFitter(const GaussTraceFitter& other)))`.
#[test]
fn section_copy_constructor() {
    let traces = class_test_traces(0.8, 0.2);
    let fitter = class_test_fitter(&traces);
    let gtf2 = fitter.clone();
    test_real_similar(fitter.center(), gtf2.center());
    test_real_similar(fitter.height(), gtf2.height());
    test_real_similar(fitter.sigma(), gtf2.sigma());
    test_real_similar(fitter.lower_rt_bound(), gtf2.lower_rt_bound());
}

/// `START_SECTION((GaussTraceFitter& operator=(const GaussTraceFitter& source)))`.
#[test]
fn section_assignment() {
    let traces = class_test_traces(0.8, 0.2);
    let fitter = class_test_fitter(&traces);
    let mut gtf3 = GaussTraceFitter::new();
    assert_ne!(gtf3, fitter);
    gtf3.clone_from(&fitter);
    test_real_similar(fitter.center(), gtf3.center());
    test_real_similar(fitter.height(), gtf3.height());
    test_real_similar(fitter.sigma(), gtf3.sigma());
    test_real_similar(fitter.lower_rt_bound(), gtf3.lower_rt_bound());
}

/// `START_SECTION((void fit(FeatureFinderAlgorithmPickedHelperStructs::MassTraces& traces)))`.
#[test]
fn section_fit() {
    let mut mts = class_test_traces(0.8, 0.2);
    let fitter = class_test_fitter(&mts);
    test_real_similar(fitter.center(), EXPECTED_X0);
    test_real_similar(fitter.height(), EXPECTED_H);
    test_real_similar(fitter.sigma(), EXPECTED_SIGMA);

    let mut weighted_fitter = GaussTraceFitter::new();
    let mut params = TraceFitterParams::defaults().unwrap();
    params
        .set_value("weighted", ParamValue::String("true".into()), "", &[])
        .unwrap();
    let (parameters, _) = TraceFitterParams::from_param(&params).unwrap();
    weighted_fitter.set_parameters(parameters);
    weighted_fitter.fit(&mts).unwrap();
    test_real_similar(weighted_fitter.center(), EXPECTED_X0);
    test_real_similar(weighted_fitter.height(), EXPECTED_H - 0.0035);
    mts[0].theoretical_int = 0.4;
    mts[1].theoretical_int = 0.6;
    weighted_fitter.fit(&mts).unwrap();
    test_real_similar(weighted_fitter.center(), EXPECTED_X0);
    test_real_similar(weighted_fitter.height(), 6.0847);
}

/// `START_SECTION((double getLowerRTBound() const))`.
#[test]
fn section_lower_rt_bound() {
    let fitter = class_test_fitter(&class_test_traces(0.8, 0.2));
    test_real_similar(fitter.lower_rt_bound(), EXPECTED_X0 - 2.5 * EXPECTED_SIGMA);
}

/// `START_SECTION((double getUpperRTBound() const))`.
#[test]
fn section_upper_rt_bound() {
    let fitter = class_test_fitter(&class_test_traces(0.8, 0.2));
    test_real_similar(fitter.upper_rt_bound(), EXPECTED_X0 + 2.5 * EXPECTED_SIGMA);
}

/// `START_SECTION((double getHeight() const))`.
#[test]
fn section_height() {
    let fitter = class_test_fitter(&class_test_traces(0.8, 0.2));
    test_real_similar(fitter.height(), 10.0);
}

/// `START_SECTION((double getCenter() const))`.
#[test]
fn section_center() {
    let fitter = class_test_fitter(&class_test_traces(0.8, 0.2));
    test_real_similar(fitter.center(), 680.1);
}

/// `START_SECTION((double getSigma() const))`.
#[test]
fn section_sigma() {
    let fitter = class_test_fitter(&class_test_traces(0.8, 0.2));
    test_real_similar(fitter.sigma(), 1.5);
}

/// `START_SECTION((bool checkMaximalRTSpan(const double max_rt_span)))`.
#[test]
fn section_check_maximal_rt_span() {
    let mts = class_test_traces(0.8, 0.2);
    let fitter = class_test_fitter(&mts);
    let mt1 = &mts[0];
    let region_rt_span = mt1.peaks[mt1.peaks.len() - 1].rt - mt1.peaks[0].rt;
    // "we add some small number to overcome precision problems on 32-bit machines"
    let mut max_rt_span = 5.0 * fitter.sigma() / region_rt_span + 0.00000000000001;
    assert!(!fitter.check_maximal_rt_span(max_rt_span));
    max_rt_span -= 0.1;
    assert!(fitter.check_maximal_rt_span(max_rt_span));
}

/// `START_SECTION((bool checkMinimalRTSpan(const std::pair<double, double> &rt_bounds, const double min_rt_span)))`.
#[test]
fn section_check_minimal_rt_span() {
    let fitter = class_test_fitter(&class_test_traces(0.8, 0.2));
    let rt_bounds = (0.0, 4.0);
    let mut min_rt_span = 0.5;
    assert!(!fitter.check_minimal_rt_span(rt_bounds, min_rt_span));
    min_rt_span += 0.5;
    assert!(fitter.check_minimal_rt_span(rt_bounds, min_rt_span));
}

/// `START_SECTION((double getValue(double rt) const))`.
#[test]
fn section_value() {
    let fitter = class_test_fitter(&class_test_traces(0.8, 0.2));
    test_real_similar(fitter.value(EXPECTED_X0), EXPECTED_H);
}

/// `START_SECTION((double computeTheoretical(const FeatureFinderAlgorithmPickedHelperStructs::MassTrace& trace, Size k)))`.
#[test]
fn section_compute_theoretical() {
    let fitter = class_test_fitter(&class_test_traces(0.8, 0.2));
    let mut mt = MassTrace {
        theoretical_int: 0.8,
        ..MassTrace::default()
    };
    mt.peaks.push(TracePeak::new(0, 0, EXPECTED_X0, 0.0, 8.0));
    test_real_similar(
        fitter.compute_theoretical(&mt, 0).unwrap(),
        mt.theoretical_int * EXPECTED_H,
    );
}

/// `START_SECTION((virtual double getArea()))`.
#[test]
fn section_area() {
    let fitter = class_test_fitter(&class_test_traces(0.8, 0.2));
    test_real_similar(fitter.area(), 2.506628 * EXPECTED_SIGMA * EXPECTED_H);
}

/// `START_SECTION((virtual std::string getGnuplotFormula(...)))`. The source
/// test reads `mts[0]` after the `fit` section set its theoretical intensity to
/// 0.4.
#[test]
fn section_gnuplot_formula() {
    let mut mts = class_test_traces(0.8, 0.2);
    let fitter = class_test_fitter(&mts);
    mts[0].theoretical_int = 0.4;
    mts[1].theoretical_int = 0.6;
    let formula = fitter.gnuplot_formula(&mts[0], 'f', 0.0, 0.0);
    // should look like -- f(x)= 0 + 7.99996 * exp(-0.5*(x-680.1)**2/(1.50001)**2) --
    assert!(formula.starts_with("f(x)= 0 + "), "{formula}");
    assert!(formula.contains("exp(-0.5*(x-"), "{formula}");
    assert!(formula.contains(")**2/("), "{formula}");
    assert!(formula.ends_with(")**2)"), "{formula}");
}

/// `START_SECTION((double getFWHM() const))`.
#[test]
fn section_fwhm() {
    let fitter = class_test_fitter(&class_test_traces(0.8, 0.2));
    test_real_similar(fitter.fwhm(), 2.35482 * EXPECTED_SIGMA);
}

// ---------------------------------------------------------------------------
// The oracle fixtures
// ---------------------------------------------------------------------------

struct Fixture {
    rows: BTreeMap<(String, String), (String, String)>,
    cases: Vec<String>,
}

impl Fixture {
    fn parse(text: &str) -> Self {
        let mut rows = BTreeMap::new();
        let mut cases: Vec<String> = Vec::new();
        for line in text.lines() {
            let fields: Vec<&str> = line.splitn(4, '\t').collect();
            assert_eq!(fields.len(), 4, "malformed fixture row {line:?}");
            if !cases.iter().any(|case| case == fields[0]) {
                cases.push(fields[0].to_owned());
            }
            let previous = rows.insert(
                (fields[0].to_owned(), fields[1].to_owned()),
                (fields[2].to_owned(), fields[3].to_owned()),
            );
            assert!(previous.is_none(), "duplicate fixture row {line:?}");
        }
        Self { rows, cases }
    }

    /// Case names starting with `prefix`, in file order.
    fn cases(&self, prefix: &str) -> Vec<String> {
        self.cases
            .iter()
            .filter(|case| case.starts_with(prefix))
            .cloned()
            .collect()
    }

    fn has(&self, case: &str, quantity: &str) -> bool {
        self.rows
            .contains_key(&(case.to_owned(), quantity.to_owned()))
    }

    #[track_caller]
    fn raw(&self, case: &str, quantity: &str, kind: &str) -> &str {
        let (found, value) = self
            .rows
            .get(&(case.to_owned(), quantity.to_owned()))
            .unwrap_or_else(|| panic!("fixture has no row {case} {quantity}"));
        assert_eq!(found, kind, "{case} {quantity}");
        value
    }

    #[track_caller]
    fn f64(&self, case: &str, quantity: &str) -> f64 {
        bits64(self.raw(case, quantity, "f64"))
    }

    #[track_caller]
    fn f64s(&self, case: &str, quantity: &str) -> Vec<f64> {
        split(self.raw(case, quantity, "f64[]"))
            .map(bits64)
            .collect()
    }

    #[track_caller]
    fn f32s(&self, case: &str, quantity: &str) -> Vec<f32> {
        split(self.raw(case, quantity, "f32[]"))
            .map(|v| f32::from_bits(u32::from_str_radix(v, 16).unwrap()))
            .collect()
    }

    #[track_caller]
    fn i64(&self, case: &str, quantity: &str) -> i64 {
        self.raw(case, quantity, "i64").parse().unwrap()
    }

    #[track_caller]
    fn i64s(&self, case: &str, quantity: &str) -> Vec<i64> {
        split(self.raw(case, quantity, "i64[]"))
            .map(|v| v.parse().unwrap())
            .collect()
    }

    #[track_caller]
    fn boolean(&self, case: &str, quantity: &str) -> bool {
        match self.raw(case, quantity, "bool") {
            "true" => true,
            "false" => false,
            other => panic!("bad bool {other}"),
        }
    }

    #[track_caller]
    fn string(&self, case: &str, quantity: &str) -> &str {
        self.raw(case, quantity, "str")
    }

    /// The traces of `case`: m/z is not recorded and not read by the fitter.
    fn traces(&self, case: &str) -> MassTraces {
        let mut traces = MassTraces::new();
        let count = self.i64(case, "traces.size");
        for t in 0..count {
            let prefix = format!("trace[{t}].");
            let rts = self.f64s(case, &format!("{prefix}rt"));
            let intensities = self.f32s(case, &format!("{prefix}intensity"));
            assert_eq!(rts.len(), intensities.len());
            let mut trace = MassTrace {
                theoretical_int: self.f64(case, &format!("{prefix}theoretical_int")),
                ..MassTrace::default()
            };
            for (k, (&rt, &intensity)) in rts.iter().zip(&intensities).enumerate() {
                trace.peaks.push(TracePeak::new(0, k, rt, 0.0, intensity));
            }
            trace.update_maximum();
            traces.push(trace);
        }
        traces.baseline = self.f64(case, "traces.baseline");
        traces.max_trace = 0;
        traces
    }
}

fn split(value: &str) -> impl Iterator<Item = &str> {
    value.split(',').filter(|v| !v.is_empty())
}

fn bits64(value: &str) -> f64 {
    f64::from_bits(u64::from_str_radix(value, 16).unwrap())
}

/// Comparison against the oracle that also records the largest deviations,
/// printed at the end of each replay.
#[derive(Default)]
struct Deviations {
    compared: usize,
    bitwise: usize,
    max_relative: BTreeMap<&'static str, f64>,
}

impl Deviations {
    #[track_caller]
    fn check(
        &mut self,
        what: &'static str,
        context: &str,
        actual: f64,
        expected: f64,
        tolerance: f64,
    ) {
        self.compared += 1;
        if actual.to_bits() == expected.to_bits() || (actual.is_nan() && expected.is_nan()) {
            self.bitwise += 1;
            self.max_relative.entry(what).or_insert(0.0);
            return;
        }
        let scale = actual.abs().max(expected.abs());
        let relative = if actual == expected {
            0.0
        } else if scale.is_finite() && scale > 0.0 {
            (actual - expected).abs() / scale
        } else {
            f64::INFINITY
        };
        let slot = self.max_relative.entry(what).or_insert(0.0);
        if relative > *slot {
            *slot = relative;
        }
        assert!(
            relative <= tolerance,
            "{context} {what}: {actual:e} vs oracle {expected:e}, relative {relative:e} > {tolerance:e}"
        );
    }

    #[track_caller]
    fn check_all(
        &mut self,
        what: &'static str,
        context: &str,
        actual: &[f64],
        expected: &[f64],
        tolerance: f64,
    ) {
        assert_eq!(actual.len(), expected.len(), "{context} {what} length");
        for (index, (&a, &e)) in actual.iter().zip(expected).enumerate() {
            self.check(what, &format!("{context}[{index}]"), a, e, tolerance);
        }
    }

    #[track_caller]
    fn expect_eq<T: PartialEq + std::fmt::Debug>(
        &mut self,
        what: &'static str,
        context: &str,
        actual: T,
        expected: T,
    ) {
        assert!(
            actual == expected,
            "{context} {what}: {actual:?} vs oracle {expected:?}"
        );
    }

    fn report(&self, name: &str) {
        eprintln!(
            "{name}: {} values compared, {} bit-identical; largest relative deviation per quantity: {:?}",
            self.compared, self.bitwise, self.max_relative
        );
    }
}

/// Everything one budgeted fit through the shared driver observes.
struct BudgetFit {
    status: Result<LmStatus, Error>,
    nfev: usize,
    njev: usize,
    x: [f64; 3],
    kinds: String,
    path: Vec<f64>,
}

/// Start values from `traces`, then [`optimize_with_status`] with the Gaussian
/// functor at `max_iteration`, counting and recording every evaluation.
fn fit_at_budget(traces: &MassTraces, weighted: bool, max_iteration: i64) -> BudgetFit {
    let parameters = TraceFitterParams {
        max_iteration,
        weighted,
    };
    let mut start = GaussTraceFitter::with_parameters(parameters);
    start.set_initial_parameters(traces).unwrap();
    let mut x = [start.height(), start.center(), start.sigma()];
    let functor = GaussTraceFunctor::new(traces, weighted);
    let nfev = Cell::new(0usize);
    let njev = Cell::new(0usize);
    let events = RefCell::new((String::new(), Vec::new()));
    let status = optimize_with_status(
        &mut x,
        functor.values(),
        |point: &[f64], fvec: &mut [f64]| {
            nfev.set(nfev.get() + 1);
            let mut events = events.borrow_mut();
            events.0.push('f');
            events.1.extend_from_slice(point);
            functor.residuals(point, fvec).unwrap();
        },
        |point: &[f64], jac: &mut DenseMatrix| {
            njev.set(njev.get() + 1);
            let mut events = events.borrow_mut();
            events.0.push('j');
            events.1.extend_from_slice(point);
            functor.jacobian(point, jac).unwrap();
        },
        &parameters,
    );
    let (kinds, path) = events.into_inner();
    BudgetFit {
        status,
        nfev: nfev.get(),
        njev: njev.get(),
        x,
        kinds,
        path,
    }
}

fn library_view(x: [f64; 3]) -> [f64; 3] {
    [x[0], x[1], x[2].abs()]
}

/// A fitter holding the oracle's fitted parameters for the queries: the start
/// values from `traces` (for the region span), then
/// `set_optimized_parameters`.
fn query_fitter(traces: &MassTraces, weighted: bool, params: [f64; 3]) -> GaussTraceFitter {
    let mut fitter = GaussTraceFitter::with_parameters(TraceFitterParams {
        max_iteration: 500,
        weighted,
    });
    fitter.set_initial_parameters(traces).unwrap();
    fitter.set_optimized_parameters(params);
    fitter
}

fn check_start_values(
    deviations: &mut Deviations,
    fixture: &Fixture,
    case: &str,
    fitter: &GaussTraceFitter,
) {
    for (what, quantity, actual) in [
        ("initial.height", "initial.height", fitter.height()),
        ("initial.x0", "initial.x0", fitter.center()),
        ("initial.sigma", "initial.sigma", fitter.sigma()),
        (
            "initial.region_rt_span",
            "initial.region_rt_span",
            fitter.region_rt_span(),
        ),
    ] {
        deviations.check(
            what,
            case,
            actual,
            fixture.f64(case, quantity),
            EXACT_TOLERANCE,
        );
    }
}

/// Residuals and the column-major Jacobian at every recorded vector.
fn check_functor(
    deviations: &mut Deviations,
    fixture: &Fixture,
    case: &str,
    traces: &MassTraces,
    weighted: bool,
) {
    let functor = GaussTraceFunctor::new(traces, weighted);
    assert_eq!(functor.inputs(), 3);
    let mut checked = 0;
    for label in [
        "x_init",
        "x_final_replica_500",
        "probe_true_10_680.1_1.5",
        "probe_negative_sigma",
        "probe_offset_8_679.5_2.0",
    ] {
        let prefix = format!("functor[{label}].");
        if !fixture.has(case, &format!("{prefix}x")) {
            continue;
        }
        checked += 1;
        let x = fixture.f64s(case, &format!("{prefix}x"));
        assert_eq!(
            usize::try_from(fixture.i64(case, &format!("{prefix}values"))).unwrap(),
            functor.values()
        );
        let mut fvec = vec![0.0; functor.values()];
        functor.residuals(&x, &mut fvec).unwrap();
        let context = format!("{case} {label}");
        deviations.check_all(
            "residuals",
            &context,
            &fvec,
            &fixture.f64s(case, &format!("{prefix}residuals")),
            EXACT_TOLERANCE,
        );
        let mut jac = DenseMatrix::zeros(functor.values(), 3);
        functor.jacobian(&x, &mut jac).unwrap();
        let expected = fixture.f64s(case, &format!("{prefix}jacobian_column_major"));
        let mut column_major = Vec::with_capacity(expected.len());
        for col in 0..3 {
            for row in 0..functor.values() {
                column_major.push(jac.at(row, col));
            }
        }
        deviations.check_all(
            "jacobian",
            &context,
            &column_major,
            &expected,
            EXACT_TOLERANCE,
        );
    }
    assert!(checked > 0, "{case}: no functor evaluation recorded");
}

/// The fit at 500 against the library fit, then every query the C2 driver
/// recorded, on the oracle's parameters.
fn check_fit500(
    deviations: &mut Deviations,
    fixture: &Fixture,
    case: &str,
    traces: &MassTraces,
    weighted: bool,
) {
    let f = |q: &str| fixture.f64(case, &format!("fit500.{q}"));
    let mut fitter = GaussTraceFitter::with_parameters(TraceFitterParams {
        max_iteration: 500,
        weighted,
    });
    fitter.fit(traces).unwrap();
    assert_eq!(
        fitter.parameters().max_iteration,
        fixture.i64(case, "fit500.member_max_iterations")
    );
    assert_eq!(
        fitter.parameters().weighted,
        fixture.boolean(case, "fit500.member_weighted")
    );
    deviations.check_all(
        "fit.params",
        case,
        &[fitter.height(), fitter.center(), fitter.sigma()],
        &[f("height"), f("center"), f("sigma")],
        FIT_TOLERANCE,
    );
    deviations.check(
        "fit.region_rt_span",
        case,
        fitter.region_rt_span(),
        f("region_rt_span"),
        EXACT_TOLERANCE,
    );

    let q = query_fitter(traces, weighted, [f("height"), f("center"), f("sigma")]);
    for (what, actual, expected) in [
        ("query.fwhm", q.fwhm(), f("fwhm")),
        ("query.area", q.area(), f("area")),
        (
            "query.lower_rt_bound",
            q.lower_rt_bound(),
            f("lower_rt_bound"),
        ),
        (
            "query.upper_rt_bound",
            q.upper_rt_bound(),
            f("upper_rt_bound"),
        ),
        ("query.value", q.value(q.center()), f("value_at_center")),
        (
            "query.value",
            q.value(q.center() + 1.0),
            f("value_at_center_plus_1"),
        ),
        (
            "query.value",
            q.value(q.center() - 2.0),
            f("value_at_center_minus_2"),
        ),
    ] {
        deviations.check(what, case, actual, expected, EXACT_TOLERANCE);
    }
    let class_max = f("arg_class_test_max_rt_span");
    let b = |name: &str| fixture.boolean(case, &format!("fit500.{name}"));
    for (what, actual, expected) in [
        (
            "query.check_maximal_rt_span",
            q.check_maximal_rt_span(class_max),
            b("check_maximal_rt_span_class_test"),
        ),
        (
            "query.check_maximal_rt_span",
            q.check_maximal_rt_span(class_max - 0.1),
            b("check_maximal_rt_span_class_test_minus_0_1"),
        ),
        (
            "query.check_maximal_rt_span",
            q.check_maximal_rt_span(f("arg_ffap_max_rt_span")),
            b("check_maximal_rt_span_ffap"),
        ),
        (
            "query.check_minimal_rt_span",
            q.check_minimal_rt_span((0.0, 4.0), 0.5),
            b("check_minimal_rt_span_0_4_0_5"),
        ),
        (
            "query.check_minimal_rt_span",
            q.check_minimal_rt_span((0.0, 4.0), 1.0),
            b("check_minimal_rt_span_0_4_1_0"),
        ),
        (
            "query.check_minimal_rt_span",
            q.check_minimal_rt_span(traces.rt_bounds().unwrap(), f("arg_ffap_min_rt_span")),
            b("check_minimal_rt_span_trace_bounds_ffap"),
        ),
    ] {
        deviations.expect_eq(what, case, actual, expected);
    }
    for (t, trace) in traces.iter().enumerate() {
        let expected = fixture.f64s(case, &format!("fit500.per_trace[{t}].compute_theoretical"));
        let actual: Vec<f64> = (0..trace.peaks.len())
            .map(|k| q.compute_theoretical(trace, k).unwrap())
            .collect();
        deviations.check_all(
            "query.compute_theoretical",
            case,
            &actual,
            &expected,
            EXACT_TOLERANCE,
        );
        let name = char::from(b'f' + u8::try_from(t).unwrap());
        let shift = 500.0 * f64::from(u32::try_from(t).unwrap());
        deviations.expect_eq(
            "query.gnuplot_formula",
            case,
            q.gnuplot_formula(trace, name, traces.baseline, shift)
                .as_str(),
            fixture.string(case, &format!("fit500.per_trace[{t}].gnuplot_formula")),
        );
    }
    deviations.expect_eq(
        "query.gnuplot_formula",
        case,
        q.gnuplot_formula(&traces[0], 'f', 0.0, 0.0).as_str(),
        fixture.string(case, "fit500.gnuplot_formula_f_0_0"),
    );
}

/// The budget sweep at the listed budgets: the library parameters (stored
/// where they change), the replica's status and, where recorded, `nfev` and
/// `njev`; and the boundary from which every result equals the result at the
/// largest budget.
fn check_sweep(
    deviations: &mut Deviations,
    fixture: &Fixture,
    case: &str,
    traces: &MassTraces,
    weighted: bool,
    budgets: &[i64],
) {
    let n_max = fixture.i64(case, "sweep.n_max");
    let statuses = fixture.i64s(case, "sweep.replica_status");
    let counts = fixture.has(case, "sweep.replica_nfev").then(|| {
        (
            fixture.i64s(case, "sweep.replica_nfev"),
            fixture.i64s(case, "sweep.replica_njev"),
        )
    });
    let mut library: Vec<(i64, Vec<f64>)> = Vec::new();
    for n in 1..=n_max {
        let quantity = format!("sweep.library[{n}]");
        if fixture.has(case, &quantity) {
            library.push((n, fixture.f64s(case, &quantity)));
        }
    }
    let reference = fit_at_budget(traces, weighted, n_max);
    let boundary = fixture.i64(case, "summary.smallest_identical_max_iteration_library");
    for &n in budgets {
        let context = format!("{case} max_iteration {n}");
        let fit = fit_at_budget(traces, weighted, n);
        let status = fit
            .status
            .as_ref()
            .unwrap_or_else(|e| panic!("{context}: {e}"));
        let index = usize::try_from(n - 1).unwrap();
        deviations.expect_eq(
            "sweep.status",
            &context,
            i64::from(status.code()),
            statuses[index],
        );
        if let Some((nfev, njev)) = &counts {
            deviations.expect_eq("sweep.nfev", &context, as_i64(fit.nfev), nfev[index]);
            deviations.expect_eq("sweep.njev", &context, as_i64(fit.njev), njev[index]);
        }
        deviations.check_all(
            "sweep.params",
            &context,
            &library_view(fit.x),
            library_at(&library, n),
            FIT_TOLERANCE,
        );
        let identical = fit.x.map(f64::to_bits) == reference.x.map(f64::to_bits);
        deviations.expect_eq("sweep.boundary", &context, identical, n >= boundary);
    }
}

fn as_i64(count: usize) -> i64 {
    i64::try_from(count).unwrap()
}

/// The library parameters at budget `n`: the last recorded change at or below
/// it.
fn library_at(library: &[(i64, Vec<f64>)], n: i64) -> &[f64] {
    &library
        .iter()
        .rev()
        .find(|(start, _)| *start <= n)
        .expect("the first budget is recorded")
        .1
}

#[test]
fn class_test_inputs_equal_the_oracle_inputs() {
    let fixture = Fixture::parse(CLASSTEST);
    for (theo1, theo2) in [(0.8, 0.2), (0.4, 0.6)] {
        let case = format!("input_traces.theo_{theo1}_{theo2}");
        let ours = class_test_traces(theo1, theo2);
        let oracle = fixture.traces(&case);
        assert_eq!(ours.len(), oracle.len());
        for (a, b) in ours.iter().zip(oracle.iter()) {
            assert_eq!(a.theoretical_int.to_bits(), b.theoretical_int.to_bits());
            assert_eq!(a.peaks.len(), b.peaks.len());
            for (p, q) in a.peaks.iter().zip(&b.peaks) {
                assert_eq!(p.rt.to_bits(), q.rt.to_bits());
                assert_eq!(p.intensity.to_bits(), q.intensity.to_bits());
            }
        }
        let profile = ours.intensity_profile().unwrap();
        let bits = |values: Vec<f64>| values.into_iter().map(f64::to_bits).collect::<Vec<_>>();
        assert_eq!(
            bits(profile.iter().map(|e| e.0).collect()),
            bits(fixture.f64s(&case, "profile.rt"))
        );
        assert_eq!(
            bits(profile.iter().map(|e| e.1).collect()),
            bits(fixture.f64s(&case, "profile.intensity"))
        );
    }
}

/// The work package's literal targets, from the C2 oracle
/// (`key_results.class_test_fits_max_iteration_500`).
#[test]
fn class_test_fits_match_the_c2_literals() {
    let unweighted = class_test_fitter(&class_test_traces(0.8, 0.2));
    let relative = |a: f64, b: f64| (a - b).abs() / b.abs();
    assert!(
        relative(unweighted.height(), 9.9995822835781674) <= FIT_TOLERANCE,
        "{}",
        unweighted.height()
    );
    assert!(
        relative(unweighted.sigma(), 1.5000586589470672) <= FIT_TOLERANCE,
        "{}",
        unweighted.sigma()
    );
    let mut weighted = GaussTraceFitter::with_parameters(TraceFitterParams {
        max_iteration: 500,
        weighted: true,
    });
    weighted.fit(&class_test_traces(0.4, 0.6)).unwrap();
    assert!(
        relative(weighted.height(), 6.0828584222534152) <= FIT_TOLERANCE,
        "{}",
        weighted.height()
    );
}

#[test]
fn class_test_cases_replay_the_oracle() {
    let fixture = Fixture::parse(CLASSTEST);
    let cases = fixture.cases("gauss_theo_");
    assert_eq!(cases.len(), 4);
    let mut deviations = Deviations::default();
    for case in &cases {
        let weighted = fixture.boolean(case, "weighted");
        assert_eq!(weighted, !case.ends_with("_unweighted"));
        let traces = class_test_traces(fixture.f64(case, "theo1"), fixture.f64(case, "theo2"));
        let mut start = GaussTraceFitter::new();
        start.set_initial_parameters(&traces).unwrap();
        check_start_values(&mut deviations, &fixture, case, &start);
        check_functor(&mut deviations, &fixture, case, &traces, weighted);
        check_fit500(&mut deviations, &fixture, case, &traces, weighted);

        let path = fit_at_budget(&traces, weighted, 500);
        deviations.expect_eq(
            "path.kinds",
            case,
            path.kinds.as_str(),
            fixture.string(case, "path.kinds"),
        );
        deviations.check_all(
            "path.x",
            case,
            &path.path,
            &fixture.f64s(case, "path.x"),
            FIT_TOLERANCE,
        );
        deviations.expect_eq(
            "path.status",
            case,
            i64::from(path.status.as_ref().unwrap().code()),
            fixture.i64(case, "path.outcome.status"),
        );
        deviations.expect_eq(
            "path.nfev",
            case,
            as_i64(path.nfev),
            fixture.i64(case, "path.outcome.nfev"),
        );
        deviations.expect_eq(
            "path.njev",
            case,
            as_i64(path.njev),
            fixture.i64(case, "path.outcome.njev"),
        );

        let budgets: Vec<i64> = (1..=fixture.i64(case, "sweep.n_max")).collect();
        check_sweep(&mut deviations, &fixture, case, &traces, weighted, &budgets);
    }
    deviations.report("class test cases");
}

/// The work package's budget boundaries: identical results from
/// `max_iteration` 47 for 0.8/0.2 (unweighted and weighted) and 31 for the
/// weighted 0.4/0.6 fit, different at every smaller budget.
#[test]
fn class_test_budget_boundaries() {
    for (theo1, theo2, weighted, boundary) in [
        (0.8, 0.2, false, 47),
        (0.8, 0.2, true, 47),
        (0.4, 0.6, true, 31),
    ] {
        let traces = class_test_traces(theo1, theo2);
        let at = |n: i64| {
            let mut fitter = GaussTraceFitter::with_parameters(TraceFitterParams {
                max_iteration: n,
                weighted,
            });
            fitter.fit(&traces).unwrap();
            [fitter.height(), fitter.center(), fitter.sigma()].map(f64::to_bits)
        };
        let reference = at(500);
        assert_eq!(
            at(boundary),
            reference,
            "{theo1}/{theo2} weighted {weighted} at {boundary}"
        );
        for n in 1..boundary {
            assert_ne!(
                at(n),
                reference,
                "{theo1}/{theo2} weighted {weighted} at {n}"
            );
        }
    }
}

#[test]
fn degenerate_cases_replay_the_oracle() {
    let fixture = Fixture::parse(DEGENERATE);
    let cases = fixture.cases("degenerate.");
    assert_eq!(cases.len(), 3);
    let mut deviations = Deviations::default();
    for case in &cases {
        let traces = fixture.traces(case);
        let mut start = GaussTraceFitter::new();
        start.set_initial_parameters(&traces).unwrap();
        check_start_values(&mut deviations, &fixture, case, &start);
        let mut fitter = GaussTraceFitter::new();
        let result = fitter.fit(&traces);
        let budget = fit_at_budget(&traces, false, 500);
        if fixture.boolean(case, "library.threw") {
            let expected = format!(
                "{}: {}",
                fixture.string(case, "library.exception.name"),
                fixture.string(case, "library.exception.what")
            );
            match result {
                Err(Error::InvalidValue(message)) => assert_eq!(message, expected, "{case}"),
                other => panic!("{case}: expected {expected}, got {other:?}"),
            }
            assert!(fixture.boolean(case, "replica.values_lt_inputs"));
            assert_eq!(budget.nfev + budget.njev, 0, "{case}: nothing is evaluated");
            // The source threw after setInitialParameters_: the fitter keeps the start values.
            assert_eq!(fitter, start, "{case}");
        } else {
            result.unwrap();
            deviations.check_all(
                "fit.params",
                case,
                &[fitter.height(), fitter.center(), fitter.sigma()],
                &fixture.f64s(case, "library.params"),
                FIT_TOLERANCE,
            );
            deviations.expect_eq(
                "replica.status",
                case,
                i64::from(budget.status.as_ref().unwrap().code()),
                fixture.i64(case, "replica.status"),
            );
            deviations.expect_eq(
                "replica.nfev",
                case,
                as_i64(budget.nfev),
                fixture.i64(case, "replica.nfev"),
            );
            deviations.expect_eq(
                "replica.njev",
                case,
                as_i64(budget.njev),
                fixture.i64(case, "replica.njev"),
            );
            deviations.check_all(
                "replica.x",
                case,
                &budget.x,
                &fixture.f64s(case, "replica.x"),
                FIT_TOLERANCE,
            );
        }
    }
    deviations.report("degenerate cases");
}

/// The 25 Gaussian fits `FeatureFinderAlgorithmPicked` runs on
/// FeatureFinderCentroided_1, with the traces its seed loop handed the fitter.
#[test]
fn feature_finder_centroided_1_seed_fits_replay_the_oracle() {
    let fixture = Fixture::parse(FFC1_SEEDS);
    let count = fixture.i64("ffc1", "seed_count");
    assert_eq!(count, 25);
    let mut deviations = Deviations::default();
    for seed in 0..count {
        let case = format!("ffc1.seed[{seed}]");
        let traces = fixture.traces(&case);
        let mut start = GaussTraceFitter::new();
        start.set_initial_parameters(&traces).unwrap();
        check_start_values(&mut deviations, &fixture, &case, &start);
        check_functor(&mut deviations, &fixture, &case, &traces, false);
        check_fit500(&mut deviations, &fixture, &case, &traces, false);

        let replica = fit_at_budget(&traces, false, 500);
        deviations.expect_eq(
            "replica500.status",
            &case,
            i64::from(replica.status.as_ref().unwrap().code()),
            fixture.i64(&case, "replica500.status"),
        );
        deviations.expect_eq(
            "replica500.nfev",
            &case,
            as_i64(replica.nfev),
            fixture.i64(&case, "replica500.nfev"),
        );
        deviations.expect_eq(
            "replica500.njev",
            &case,
            as_i64(replica.njev),
            fixture.i64(&case, "replica500.njev"),
        );
        deviations.check_all(
            "replica.x",
            &case,
            &replica.x,
            &fixture.f64s(&case, "replica500.x"),
            FIT_TOLERANCE,
        );

        // Every budget up to two past natural termination, and a spread above.
        let natural = fixture.i64(
            &case,
            "summary.first_max_iteration_with_natural_termination",
        );
        let mut budgets: Vec<i64> = (1..=(natural + 2)).collect();
        budgets.extend(
            [100, 131, 250, 499, 500]
                .into_iter()
                .filter(|&n| n > natural + 2),
        );
        check_sweep(&mut deviations, &fixture, &case, &traces, false, &budgets);
    }
    deviations.report("FeatureFinderCentroided_1 seed fits");
}

// ---------------------------------------------------------------------------
// The B4-GAUSS driver's cases
// ---------------------------------------------------------------------------

#[test]
fn fit_failures_match_the_oracle() {
    let fixture = Fixture::parse(EXTRA);
    let cases = fixture.cases("fit_error.");
    assert_eq!(cases.len(), 4);
    let mut deviations = Deviations::default();
    for case in &cases {
        let traces = fixture.traces(case);
        let mut start = GaussTraceFitter::new();
        start.set_initial_parameters(&traces).unwrap();
        check_start_values(&mut deviations, &fixture, case, &start);
        let mut fitter = GaussTraceFitter::with_parameters(TraceFitterParams {
            max_iteration: fixture.i64(case, "max_iteration"),
            weighted: false,
        });
        assert!(fixture.boolean(case, "fit.threw"));
        let expected = format!(
            "{}: {}",
            fixture.string(case, "fit.exception.name"),
            fixture.string(case, "fit.exception.what")
        );
        match fitter.fit(&traces) {
            Err(Error::InvalidValue(message)) => assert_eq!(message, expected, "{case}"),
            other => panic!("{case}: expected {expected}, got {other:?}"),
        }
        for (what, actual) in [
            ("after.height", fitter.height()),
            ("after.x0", fitter.center()),
            ("after.sigma", fitter.sigma()),
            ("after.region_rt_span", fitter.region_rt_span()),
        ] {
            deviations.check(what, case, actual, fixture.f64(case, what), EXACT_TOLERANCE);
        }
    }
    deviations.report("fit failures");
}

#[test]
fn start_value_boundaries_match_the_oracle() {
    // Every start value, the query arithmetic and the gnuplot text agree bit for
    // bit in every case; the fitted parameters of two fits do not reach 1e-9
    // (`leading_max` and `trailing_max`; see `ill_conditioned_fit_tolerance`,
    // which keeps a measured bound for two more that now do). Those two are
    // where this macOS-generated oracle disagrees with a solver that reproduces
    // Eigen as the Linux x86_64 Release build compiles it. The driver recorded
    // no functor evaluations for these cases, so residuals and Jacobians are
    // not compared here.
    let fixture = Fixture::parse(EXTRA);
    let cases = fixture.cases("start.");
    assert_eq!(cases.len(), 9);
    for case in &cases {
        let mut deviations = Deviations::default();
        let traces = fixture.traces(case);
        let profile = traces.intensity_profile().unwrap();
        let rt: Vec<f64> = profile.iter().map(|e| e.0).collect();
        let intensity: Vec<f64> = profile.iter().map(|e| e.1).collect();
        deviations.check_all("profile", case, &rt, &fixture.f64s(case, "profile.rt"), 0.0);
        deviations.check_all(
            "profile",
            case,
            &intensity,
            &fixture.f64s(case, "profile.intensity"),
            0.0,
        );

        let mut start = GaussTraceFitter::new();
        start.set_initial_parameters(&traces).unwrap();
        check_start_values(&mut deviations, &fixture, case, &start);

        assert!(!fixture.boolean(case, "fit.threw"), "{case}");
        let f = |q: &str| fixture.f64(case, &format!("fit.{q}"));
        let mut fitter = GaussTraceFitter::new();
        fitter.fit(&traces).unwrap();
        deviations.check_all(
            "fit.params",
            case,
            &[fitter.height(), fitter.center(), fitter.sigma()],
            &[f("height"), f("x0"), f("sigma")],
            ill_conditioned_fit_tolerance(case).unwrap_or(FIT_TOLERANCE),
        );
        deviations.check(
            "fit.region_rt_span",
            case,
            fitter.region_rt_span(),
            f("region_rt_span"),
            EXACT_TOLERANCE,
        );

        let q = query_fitter(&traces, false, [f("height"), f("x0"), f("sigma")]);
        for (what, actual, expected) in [
            ("query.fwhm", q.fwhm(), f("fwhm")),
            ("query.area", q.area(), f("area")),
            (
                "query.lower_rt_bound",
                q.lower_rt_bound(),
                f("lower_rt_bound"),
            ),
            (
                "query.upper_rt_bound",
                q.upper_rt_bound(),
                f("upper_rt_bound"),
            ),
            ("query.value", q.value(q.center()), f("value_at_center")),
            (
                "query.value",
                q.value(q.center() + 0.7),
                f("value_at_center_plus_0.7"),
            ),
        ] {
            deviations.check(what, case, actual, expected, EXACT_TOLERANCE);
        }
        deviations.expect_eq(
            "query.gnuplot_formula",
            case,
            q.gnuplot_formula(&traces[0], 'f', traces.baseline, 0.0)
                .as_str(),
            fixture.string(case, "fit.gnuplot_f"),
        );
        deviations.report(case);
    }
}

/// The measured bound for a driver case whose fit is too ill-conditioned for
/// 1e-9, or `None` for the work package's tolerance.
///
/// These are this package's own boundary cases, not the work package's targets.
///
/// The expected values are the oracle's; the bounds are not. Each bound is the
/// next power of ten above the port's own largest measured deviation of height,
/// centre and sigma. Re-measured on 2026-09-15 against the solver of package
/// B3b-LM-FIDELITY, which reproduces Eigen's reduction kernels
/// (`docs/DISTRIBUTION_FITTERS_SUPPORT.md` §1), on Linux x86-64 with glibc
/// (dax) and on macOS arm64 with Apple libm:
///
/// - `n4_boundary`: bit-identical on both, was 1.40e-9.
/// - `merged_profile`: 2.69e-11 on Linux, bit-identical on macOS, was 4.41e-9.
/// - `leading_max` (maximum at the first retention time, sigma 0.25): 2.06e-3
///   on both (2.0614474501769614e-3 Linux, 2.0614474501789866e-3 macOS), was
///   2.93e-4. **This one rose**, and it is the only quantity in this package
///   that the new solver moves away from its oracle; see below and
///   `docs/TRACE_FITTER_SUPPORT.md`.
/// - `trailing_max`: 1.72e-3 on Linux, unchanged; on macOS it moved from
///   1.49e-3 to the same 1.72e-3, well inside the bound.
///
/// The first two now sit under the package's own 1e-9 fit tolerance on both
/// measured platforms. Their 1e-8 bounds are kept as headroom for the targets
/// this package could not measure (the `cross-platform` CI job also builds
/// Windows, whose `exp` was never measured here), not because the deviation
/// needs them.
///
/// `leading_max` rose because the oracle is macOS-generated while the solver
/// now reproduces Eigen as the **Linux x86_64 Release** build compiles it - the
/// user's decision of 2026-09-15, recorded in
/// `docs/DISTRIBUTION_FITTERS_SUPPORT.md` §1. Eigen's arm64 kernels fuse their
/// lanes (`vfmaq_f64`) and the x86_64 ones do not, so one unfused Rust path
/// cannot match both C++ builds; against the macOS SDK the port keeps 21 of 141
/// traced evaluation paths. This ill-conditioned start-value probe is where
/// that shows up. Everything else in this package improved: the two deviations
/// above fell to bit-identical and 2.69e-11, the class-test fits from 2.51e-12
/// to 1.44e-12 and their evaluation path from 1.79e-11 to 9.08e-12, and the
/// FeatureFinderCentroided_1 seed fits from 6.36e-10 to 1.83e-10.
///
/// Only the start values are known to equal the oracle's bit for bit; the
/// driver recorded no residuals or Jacobians for these cases. The gap persists
/// with the oracle platform's own `exp` and `log`, so it does not come from
/// them.
fn ill_conditioned_fit_tolerance(case: &str) -> Option<f64> {
    match case {
        "start.n4_boundary" | "start.merged_profile" => Some(1e-8),
        "start.leading_max" => Some(1e-2),
        "start.trailing_max" => Some(1e-2),
        _ => None,
    }
}

#[test]
fn gnuplot_number_formatting_matches_the_oracle() {
    let fixture = Fixture::parse(EXTRA);
    let case = "gnuplot";
    let traces = fixture.traces(case);
    let params = [
        fixture.f64(case, "fit.height"),
        fixture.f64(case, "fit.x0"),
        fixture.f64(case, "fit.sigma"),
    ];
    let mut deviations = Deviations::default();
    let mut fitter = GaussTraceFitter::new();
    fitter.fit(&traces).unwrap();
    deviations.check_all(
        "fit.params",
        case,
        &[fitter.height(), fitter.center(), fitter.sigma()],
        &params,
        FIT_TOLERANCE,
    );
    let q = query_fitter(&traces, false, params);
    for (label, name, baseline, shift, trace) in [
        ("f_0_0_t0", 'f', 0.0, 0.0, 0),
        (
            "g_baseline_1234567_shift_-680.1_t1",
            'g',
            1234567.0,
            -680.1,
            1,
        ),
        ("z_baseline_-0_shift_1e-5_t0", 'z', -0.0, 1e-5, 0),
        (
            "h_baseline_0.000123456789_shift_1e7_t1",
            'h',
            0.000123456789,
            1e7,
            1,
        ),
        ("q_baseline_-2.5_shift_-1e-300_t0", 'q', -2.5, -1e-300, 0),
    ] {
        assert_eq!(
            q.gnuplot_formula(&traces[trace], name, baseline, shift),
            fixture.string(case, &format!("formula.{label}")),
            "{label}"
        );
    }
    deviations.report("gnuplot");
}

// ---------------------------------------------------------------------------
// Known gap: the solver beyond the fixtures (report only)
// ---------------------------------------------------------------------------

/// The review probe's 79 inputs with the executed C++ results
/// (`../oracle/gauss-trace-fitter/solver-gap`).
const SOLVER_GAP: &str = include_str!("data/gauss_trace_fitter/solver_gap.tsv");

/// `|actual - expected| / max(|actual|, |expected|)`, 0 for equal values and
/// for two NaNs, infinite when the scale is zero or not finite.
fn relative_deviation(actual: f64, expected: f64) -> f64 {
    if actual == expected || (actual.is_nan() && expected.is_nan()) {
        return 0.0;
    }
    let scale = actual.abs().max(expected.abs());
    if scale.is_finite() && scale > 0.0 {
        (actual - expected).abs() / scale
    } else {
        f64::INFINITY
    }
}

/// Whether two floating-point values have the same bits, counting any two
/// NaNs as equal.
fn same_bits(actual: f64, expected: f64) -> bool {
    actual.to_bits() == expected.to_bits() || (actual.is_nan() && expected.is_nan())
}

/// The residual-evaluation points of a [`BudgetFit`], three values each,
/// without the Jacobian evaluations.
fn residual_points(fit: &BudgetFit) -> Vec<&[f64]> {
    fit.kinds
        .chars()
        .zip(fit.path.chunks(3))
        .filter(|(kind, _)| *kind == 'f')
        .map(|(_, point)| point)
        .collect()
}

/// What the solver's first step reads is the library's, on the review probe's
/// 79 inputs.
///
/// The start vector and region span come from the library's
/// `setInitialParameters_`: the vector is the replica's first residual
/// evaluation point (and the functor probe's), the span the library fit's.
/// The residuals and the column-major Jacobian at that vector come from the
/// library's `GaussTraceFunctor`. All are compared within 1e-14 relative, as
/// every other start value, residual and Jacobian is. This part of the fit
/// belongs to this package and holds on these inputs; the departure that
/// `solver_gap_probe_reports_the_known_gap` reports begins after it, inside
/// the solver.
#[test]
fn solver_gap_inputs_first_step_inputs_match_the_oracle() {
    let fixture = Fixture::parse(SOLVER_GAP);
    let cases = fixture.cases("gap.");
    assert_eq!(cases.len(), 79);
    let mut deviations = Deviations::default();
    for case in &cases {
        let traces = fixture.traces(case);
        let weighted = fixture.boolean(case, "weighted");
        let mut start = GaussTraceFitter::new();
        start.set_initial_parameters(&traces).unwrap();
        let x_start = [start.height(), start.center(), start.sigma()];
        let path = fixture.f64s(case, "replica.path");
        assert!(path.len() >= 3, "{case}: no residual evaluation recorded");
        deviations.check_all("start vector", case, &x_start, &path[..3], EXACT_TOLERANCE);
        deviations.check_all(
            "start vector",
            case,
            &x_start,
            &fixture.f64s(case, "functor[x_init].x"),
            EXACT_TOLERANCE,
        );
        deviations.check(
            "region_rt_span",
            case,
            start.region_rt_span(),
            fixture.f64(case, "library.region_rt_span"),
            EXACT_TOLERANCE,
        );
        check_functor(&mut deviations, &fixture, case, &traces, weighted);
    }
    deviations.report("solver-gap probe: start values, residuals and Jacobians at the start");
}

/// A known gap, reported and not asserted: the port's Levenberg-Marquardt
/// path against the executed Eigen solver on inputs outside the C2 and B4
/// fixtures.
///
/// The fixture holds the review probe of B4-GAUSS round 2: 12 edge cases,
/// 7 budget cases and 60 seeded random Gaussian sets (1 to 4 traces, 3 to 40
/// peaks, 0 to 30% noise, weighted or not, budget 1 to 60 or 500). For each it
/// records the product-SDK `GaussTraceFitter::fit` (tier 1) and the review's
/// Eigen replica of `optimize_` on the library's own functor (adapted: status,
/// `nfev`, `njev`, the raw final vector and every residual-evaluation point),
/// which reproduces the library's final parameters bit for bit in 79 of 79
/// cases. All of it ran on macOS arm64.
///
/// The port's residual path departs from the replica's in the last bits in
/// 64 of the 79 cases on macOS arm64 and 65 on Linux x86-64, 30 of them
/// already at the first trial step (evaluation 1), from start vectors,
/// residuals and Jacobians that are identical
/// (`solver_gap_inputs_first_step_inputs_match_the_oracle`). On these inputs
/// 20 fits (21 on Linux) then miss the 1e-9 fit tolerance, and one status and
/// some `nfev` counts differ (`docs/TRACE_FITTER_SUPPORT.md`, "Known gap").
///
/// The transcription defect this probe was written for is fixed (package
/// B3b-LM-FIDELITY; every count above improved). What is left is the platform
/// split Eigen itself has: its arm64 kernels fuse their `pmadd` lanes and its
/// x86_64 `-mssse3` kernels do not, this fixture is from the fused macOS arm64
/// SDK, and the user decided on 2026-09-15 that the port matches the unfused
/// Linux x86_64 Release build on every target
/// (`docs/DISTRIBUTION_FITTERS_SUPPORT.md` §1). So this stays a report rather
/// than becoming an assertion: run it with `--ignored --nocapture`. It prints
/// one line per case and a summary, asserts only the fixture's shape, never a
/// Rust value, and the numbers it prints are measurements of the current port,
/// not expectations. The asserted replay of the same 79 inputs against a Linux
/// x86_64 Release trace of Eigen, where the port is bit-identical, is
/// `tests/lm_eigen_path_differential.rs`.
#[test]
#[ignore = "macOS-generated oracle against a solver that matches Linux x86_64 Release Eigen; prints a report, asserts no Rust value"]
fn solver_gap_probe_reports_the_known_gap() {
    let fixture = Fixture::parse(SOLVER_GAP);
    let cases = fixture.cases("gap.");
    assert_eq!(cases.len(), 79);

    let mut start_identical = 0usize;
    let mut paths_differ = 0usize;
    let mut first_step = 0usize;
    let mut latest_first = 0usize;
    let mut first_deviation = (f64::INFINITY, 0.0f64);
    let mut values_identical = 0usize;
    let mut outcome_differs = Vec::new();
    let mut beyond_natural = Vec::new();
    let mut beyond_exhausted = Vec::new();
    let mut short_budget_largest = 0.0f64;
    let mut status_differs = Vec::new();
    let mut nfev_differs = Vec::new();
    let mut njev_differs = 0usize;

    for case in &cases {
        let traces = fixture.traces(case);
        let max_iteration = fixture.i64(case, "max_iteration");
        let weighted = fixture.boolean(case, "weighted");
        let name = case.trim_start_matches("gap.");

        // The library fit (tier 1).
        let mut fitter = GaussTraceFitter::with_parameters(TraceFitterParams {
            max_iteration,
            weighted,
        });
        let outcome = match fitter.fit(&traces) {
            Ok(()) => "ok".to_owned(),
            Err(error) => error.to_string(),
        };
        let expected_outcome = fixture.string(case, "library.outcome");
        if outcome != expected_outcome {
            outcome_differs.push(name.to_owned());
        }
        let mut expected = fixture.f64s(case, "library.params");
        assert_eq!(expected.len(), 3, "{case} library.params");
        expected.push(fixture.f64(case, "library.region_rt_span"));
        let actual = [
            fitter.height(),
            fitter.center(),
            fitter.sigma(),
            fitter.region_rt_span(),
        ];
        values_identical += actual
            .iter()
            .zip(&expected)
            .filter(|(a, e)| same_bits(**a, **e))
            .count();
        let fit_deviation = actual[..3]
            .iter()
            .zip(&expected[..3])
            .map(|(a, e)| relative_deviation(*a, *e))
            .fold(0.0, f64::max);

        // The replica (adapted): status, counts and the residual path.
        let expected_status = fixture.i64(case, "replica.status");
        let expected_nfev = fixture.i64(case, "replica.nfev");
        let expected_njev = fixture.i64(case, "replica.njev");
        let expected_path = fixture.f64s(case, "replica.path");
        assert_eq!(
            expected_path.len(),
            3 * usize::try_from(expected_nfev).unwrap(),
            "{case} replica.path"
        );
        let expected_points: Vec<&[f64]> = expected_path.chunks(3).collect();
        let run = fit_at_budget(&traces, weighted, max_iteration);
        let status = run
            .status
            .as_ref()
            .map(|s| i64::from(s.code()))
            .map_err(|e| e.to_string());
        let points = residual_points(&run);
        let first_difference = points
            .iter()
            .zip(&expected_points)
            .position(|(a, e)| a.iter().zip(e.iter()).any(|(a, e)| !same_bits(*a, *e)))
            .or_else(|| {
                (points.len() != expected_points.len())
                    .then(|| points.len().min(expected_points.len()))
            });
        if points
            .first()
            .zip(expected_points.first())
            .is_some_and(|(a, e)| a.iter().zip(e.iter()).all(|(a, e)| same_bits(*a, *e)))
        {
            start_identical += 1;
        }
        let mut divergence = String::from("none");
        if let Some(index) = first_difference {
            paths_differ += 1;
            if index == 1 {
                first_step += 1;
            }
            latest_first = latest_first.max(index);
            if let (Some(a), Some(e)) = (points.get(index), expected_points.get(index)) {
                let deviation = a
                    .iter()
                    .zip(e.iter())
                    .map(|(a, e)| relative_deviation(*a, *e))
                    .fold(0.0, f64::max);
                first_deviation = (
                    first_deviation.0.min(deviation),
                    first_deviation.1.max(deviation),
                );
                divergence = format!("evaluation {index} (relative {deviation:.1e})");
            } else {
                divergence = format!("evaluation {index} (one path ends)");
            }
        }
        if status != Ok(expected_status) {
            status_differs.push(format!(
                "{name}: Rust {status:?}/{} vs Eigen {expected_status}/{expected_nfev}",
                run.nfev
            ));
        }
        if as_i64(run.nfev) != expected_nfev && expected_status != 5 {
            nfev_differs.push(format!("{name} {} vs {expected_nfev}", run.nfev));
        }
        if as_i64(run.njev) != expected_njev {
            njev_differs += 1;
        }
        if fit_deviation > FIT_TOLERANCE {
            let entry = format!(
                "{name} ({fit_deviation:.2e}, Eigen status {expected_status}, nfev {expected_nfev})"
            );
            if expected_status == 5 {
                beyond_exhausted.push(entry);
            } else {
                beyond_natural.push(entry);
            }
        }
        if expected_status == 5 && max_iteration < 500 {
            short_budget_largest = short_budget_largest.max(fit_deviation);
        }
        eprintln!(
            "GAP {name}: budget {max_iteration}, weighted {weighted}; outcome {outcome:?} vs {expected_outcome:?}; \
             fit relative deviation {fit_deviation:.2e}; status {status:?} vs {expected_status}; \
             nfev {} vs {expected_nfev}; njev {} vs {expected_njev}; first differing residual evaluation: {divergence}",
            run.nfev, run.njev
        );
    }

    eprintln!("GAP summary over {} cases:", cases.len());
    eprintln!("  start vector (evaluation 0) bit-identical: {start_identical}");
    eprintln!(
        "  residual paths differing: {paths_differ} ({first_step} at evaluation 1, latest first difference at evaluation {latest_first}); relative deviation at the first difference {:.1e} to {:.1e}",
        first_deviation.0, first_deviation.1
    );
    eprintln!(
        "  final height, centre, sigma, span bit-identical: {values_identical} of {}",
        4 * cases.len()
    );
    eprintln!("  library outcome differs: {outcome_differs:?}");
    eprintln!(
        "  fits beyond {FIT_TOLERANCE:e}: {} natural terminations {beyond_natural:?}; {} exhausted budgets {beyond_exhausted:?}",
        beyond_natural.len(),
        beyond_exhausted.len()
    );
    eprintln!(
        "  largest fit deviation of the budget-limited fits below 500: {short_budget_largest:.2e}"
    );
    eprintln!("  status differs: {status_differs:?}");
    eprintln!(
        "  nfev differs at natural termination: {} {nfev_differs:?}; njev differs: {njev_differs}",
        nfev_differs.len()
    );
}

// ---------------------------------------------------------------------------
// Native contracts
// ---------------------------------------------------------------------------

#[test]
fn traces_without_peaks_are_refused_before_anything_changes() {
    let mut fitter = GaussTraceFitter::new();
    fitter.fit(&class_test_traces(0.8, 0.2)).unwrap();
    let before = fitter.clone();
    let mut one_empty_trace = MassTraces::new();
    one_empty_trace.push(MassTrace::default());
    for traces in [MassTraces::new(), one_empty_trace] {
        match fitter.fit(&traces) {
            Err(Error::InvalidValue(message)) => {
                assert_eq!(
                    message,
                    "UnableToFit-FinalSet: Skipping feature, we always expect N>=p"
                );
            }
            other => panic!("{other:?}"),
        }
        assert_eq!(fitter, before);
        assert!(
            GaussTraceFitter::new()
                .set_initial_parameters(&traces)
                .is_err()
        );
    }
}

#[test]
fn optimized_parameters_keep_the_absolute_sigma() {
    let mut fitter = GaussTraceFitter::new();
    fitter.set_optimized_parameters([10.0, 680.1, -1.5]);
    assert_eq!(fitter.height(), 10.0);
    assert_eq!(fitter.center(), 680.1);
    assert_eq!(fitter.sigma(), 1.5);
}

#[test]
fn a_clone_keeps_the_region_span() {
    let mut fitter = GaussTraceFitter::new();
    fitter.fit(&class_test_traces(0.8, 0.2)).unwrap();
    let copy = fitter.clone();
    assert_eq!(
        copy.region_rt_span().to_bits(),
        fitter.region_rt_span().to_bits()
    );
    assert_eq!(
        copy.check_maximal_rt_span(0.5),
        fitter.check_maximal_rt_span(0.5)
    );
}

#[test]
fn compute_theoretical_refuses_an_index_past_the_peaks() {
    let traces = class_test_traces(0.8, 0.2);
    let fitter = class_test_fitter(&traces);
    assert!(fitter.compute_theoretical(&traces[0], 20).is_ok());
    assert!(matches!(
        fitter.compute_theoretical(&traces[0], 21),
        Err(Error::InvalidValue(_))
    ));
}

#[test]
fn the_functor_refuses_mismatched_dimensions() {
    let traces = class_test_traces(0.8, 0.2);
    let functor = GaussTraceFunctor::new(&traces, false);
    assert_eq!(functor.values(), 42);
    let mut fvec = vec![7.0; 42];
    assert!(functor.residuals(&[1.0, 2.0], &mut fvec).is_err());
    assert!(
        functor
            .residuals(&[1.0, 2.0, 3.0], &mut fvec[..41])
            .is_err()
    );
    assert!(fvec.iter().all(|&v| v == 7.0));
    let mut jac = DenseMatrix::zeros(42, 4);
    assert!(functor.jacobian(&[1.0, 2.0, 3.0], &mut jac).is_err());
    let mut jac = DenseMatrix::zeros(41, 3);
    assert!(functor.jacobian(&[1.0, 2.0, 3.0], &mut jac).is_err());
    assert!(
        functor
            .jacobian(&[1.0, 2.0, 3.0, 4.0], &mut DenseMatrix::zeros(42, 3))
            .is_err()
    );
}

/// The feature finder holds the chosen fitter as a trait object.
#[test]
fn the_fitter_works_through_a_trait_object() {
    let traces = class_test_traces(0.8, 0.2);
    let mut fitter: Box<dyn TraceFitter> = Box::new(GaussTraceFitter::new());
    fitter.set_parameters(TraceFitterParams {
        max_iteration: 500,
        weighted: false,
    });
    fitter.fit(&traces).unwrap();
    test_real_similar(fitter.center(), EXPECTED_X0);
    let direct = class_test_fitter(&traces);
    assert_eq!(fitter.height().to_bits(), direct.height().to_bits());
}

/// Non-finite input never panics; the result is whatever the arithmetic gives,
/// or an error where the helper structures refuse the input.
#[test]
fn non_finite_input_does_not_panic() {
    let mut cases = Vec::new();
    let mut nan_intensity = class_test_traces(0.8, 0.2);
    nan_intensity[0].peaks[3].intensity = f32::NAN;
    cases.push(nan_intensity);
    let mut infinite_intensity = class_test_traces(0.8, 0.2);
    infinite_intensity[1].peaks[10].intensity = f32::INFINITY;
    cases.push(infinite_intensity);
    let mut nan_theoretical = class_test_traces(0.8, 0.2);
    nan_theoretical[1].theoretical_int = f64::NAN;
    cases.push(nan_theoretical);
    let mut nan_rt = class_test_traces(0.8, 0.2);
    nan_rt[1].peaks[5].rt = f64::NAN;
    cases.push(nan_rt);
    let mut infinite_baseline = class_test_traces(0.8, 0.2);
    infinite_baseline.baseline = f64::INFINITY;
    cases.push(infinite_baseline);
    for traces in &cases {
        for weighted in [false, true] {
            let mut fitter = GaussTraceFitter::with_parameters(TraceFitterParams {
                max_iteration: 500,
                weighted,
            });
            let _ = fitter.fit(traces);
            let _ = fitter.gnuplot_formula(&traces[0], 'f', traces.baseline, 0.0);
        }
    }
}
