// Copyright (c) 2002-present, OpenMS Inc. -- EKU Tuebingen, ETH Zurich, and FU Berlin
// SPDX-License-Identifier: BSD-3-Clause
// $Maintainer: OpenMS Rust contributors $
//! Port of `RankData_test.cpp` (core SDK bc9cc12): one test per
//! `START_SECTION`, cited by source line. The vectors of the cross-validation
//! section were generated by the source's authors with SciPy 1.17.1 and are
//! transcribed here (tier 3); the small hand-computed vectors are derived from
//! the documented tie rules.

use openms::Error;
use openms::math::rank_data::{
    NanPolicy, RankMethod, rankdata, rankdata_f32, rankdata_f64, rankdata_i32,
};

const NAN: f64 = f64::NAN;

/// Element-wise comparison in which a NaN matches only a NaN.
fn expect(actual: &[f64], expected: &[f64]) {
    assert_eq!(actual.len(), expected.len());
    for (index, (got, want)) in actual.iter().zip(expected.iter()).enumerate() {
        if want.is_nan() {
            assert!(got.is_nan(), "index {index}: {got} is not NaN");
        } else {
            assert!(
                (got - want).abs() <= 1e-12,
                "index {index}: {got} != {want}"
            );
        }
    }
}

// L60 rankdata - basic tie methods on doubles
#[test]
fn section_basic_tie_methods() {
    let a = [0.0, 2.0, 3.0, 2.0];
    let p = NanPolicy::Propagate;
    // Sorted: 0, 2, 2, 3 at one-based ranks 1, 2, 3, 4. The tied 2s span ranks
    // 2..3, so Average is 2.5, Min is 2, Max is 3 and Dense is the second
    // distinct value.
    expect(
        &rankdata(&a, RankMethod::Average, p).unwrap(),
        &[1.0, 2.5, 4.0, 2.5],
    );
    expect(
        &rankdata(&a, RankMethod::Min, p).unwrap(),
        &[1.0, 2.0, 4.0, 2.0],
    );
    expect(
        &rankdata(&a, RankMethod::Max, p).unwrap(),
        &[1.0, 3.0, 4.0, 3.0],
    );
    expect(
        &rankdata(&a, RankMethod::Dense, p).unwrap(),
        &[1.0, 2.0, 3.0, 2.0],
    );
    expect(
        &rankdata(&a, RankMethod::Ordinal, p).unwrap(),
        &[1.0, 2.0, 4.0, 3.0],
    );
    // Average is the default of both enums.
    assert_eq!(RankMethod::default(), RankMethod::Average);
    assert_eq!(NanPolicy::default(), NanPolicy::Propagate);
}

// L80 rankdata - all-equal values and ordinal stability
#[test]
fn section_all_equal_values() {
    let a = [5.0, 5.0, 5.0];
    let p = NanPolicy::Propagate;
    expect(
        &rankdata(&a, RankMethod::Average, p).unwrap(),
        &[2.0, 2.0, 2.0],
    );
    expect(&rankdata(&a, RankMethod::Min, p).unwrap(), &[1.0, 1.0, 1.0]);
    expect(&rankdata(&a, RankMethod::Max, p).unwrap(), &[3.0, 3.0, 3.0]);
    expect(
        &rankdata(&a, RankMethod::Dense, p).unwrap(),
        &[1.0, 1.0, 1.0],
    );
    // Ordinal breaks the tie by original order, which the stable sort provides.
    expect(
        &rankdata(&a, RankMethod::Ordinal, p).unwrap(),
        &[1.0, 2.0, 3.0],
    );
}

// L100 rankdata - NaN policy: propagate
#[test]
fn section_nan_policy_propagate() {
    let a = [0.0, 2.0, 3.0, NAN, -2.0, NAN];
    let r = rankdata(&a, RankMethod::Average, NanPolicy::Propagate).unwrap();
    assert_eq!(r.len(), a.len());
    assert!(r.iter().all(|value| value.is_nan()));
}

// L116 rankdata - NaN policy: omit
#[test]
fn section_nan_policy_omit() {
    let a = [0.0, 2.0, 3.0, NAN, -2.0, NAN];
    let r = rankdata(&a, RankMethod::Average, NanPolicy::Omit).unwrap();
    assert_eq!(r.len(), a.len());
    // Ranking only [-2, 0, 2, 3] as 1..4.
    expect(&r, &[2.0, 3.0, 4.0, NAN, 1.0, NAN]);
}

// L138 rankdata - NaN policy: raise
#[test]
fn section_nan_policy_raise() {
    let a = [1.0, NAN, 2.0];
    // The source throws std::invalid_argument.
    assert!(matches!(
        rankdata(&a, RankMethod::Average, NanPolicy::Raise).unwrap_err(),
        Error::InvalidValue(_)
    ));
    // Without a NaN the policy changes nothing.
    expect(
        &rankdata(&[1.0, 3.0, 2.0], RankMethod::Average, NanPolicy::Raise).unwrap(),
        &[1.0, 3.0, 2.0],
    );
}

// L159 rankdata - integer input support
#[test]
fn section_integer_input() {
    let ai = [3, 3, 1];
    let p = NanPolicy::Propagate;
    // Sorted [1, 3, 3] at ranks [1, 2, 3]; the two 3s average to 2.5.
    expect(
        &rankdata(&ai, RankMethod::Average, p).unwrap(),
        &[2.5, 2.5, 1.0],
    );
    expect(
        &rankdata(&ai, RankMethod::Min, p).unwrap(),
        &[2.0, 2.0, 1.0],
    );
    expect(
        &rankdata(&ai, RankMethod::Max, p).unwrap(),
        &[3.0, 3.0, 1.0],
    );
    expect(
        &rankdata(&ai, RankMethod::Dense, p).unwrap(),
        &[2.0, 2.0, 1.0],
    );
    // Ordinal keeps the first 3 ahead of the second.
    expect(
        &rankdata(&ai, RankMethod::Ordinal, p).unwrap(),
        &[2.0, 3.0, 1.0],
    );
    // An integer can never be NaN, so no policy can change the result.
    expect(
        &rankdata(&ai, RankMethod::Average, NanPolicy::Raise).unwrap(),
        &[2.5, 2.5, 1.0],
    );
}

// L182 RankData free-function overloads by value
#[test]
fn section_free_function_overloads() {
    let p = NanPolicy::Propagate;
    let ad = [0.0, 2.0, 2.0];
    expect(
        &rankdata_f64(&ad, RankMethod::Min, p).unwrap(),
        &[1.0, 2.0, 2.0],
    );
    let af = [0.0f32, 2.0, 3.0, 2.0];
    expect(
        &rankdata_f32(&af, RankMethod::Dense, p).unwrap(),
        &[1.0, 2.0, 3.0, 2.0],
    );
    let ai = [5, 5, 1];
    expect(
        &rankdata_i32(&ai, RankMethod::Average, p).unwrap(),
        &[2.5, 2.5, 1.0],
    );
}

// L210 rankdata - NaN policy: omit with all-NaN input
#[test]
fn section_omit_with_all_nan_input() {
    let a = [NAN, NAN, NAN];
    let r = rankdata(&a, RankMethod::Average, NanPolicy::Omit).unwrap();
    assert_eq!(r.len(), 3);
    assert!(r.iter().all(|value| value.is_nan()));
}

// L224 rankdata - ordinal stability across two tie blocks
#[test]
fn section_ordinal_across_two_tie_blocks() {
    let a = [3.0, 3.0, 1.0, 1.0];
    // Stable sorted positions by value: [2, 3, 0, 1], so the ranks map back to
    // [3, 4, 1, 2].
    expect(
        &rankdata(&a, RankMethod::Ordinal, NanPolicy::Propagate).unwrap(),
        &[3.0, 4.0, 1.0, 2.0],
    );
}

// L241 rankdata - empty input
#[test]
fn section_empty_input() {
    let empty: [f64; 0] = [];
    let r = rankdata(&empty, RankMethod::Average, NanPolicy::Propagate).unwrap();
    assert_eq!(r.len(), 0);
    // Every policy agrees on an empty input, including Raise.
    assert_eq!(
        rankdata(&empty, RankMethod::Ordinal, NanPolicy::Raise)
            .unwrap()
            .len(),
        0
    );
}

// L249 rankdata - scipy.stats.rankdata cross-validation
#[test]
fn section_scipy_cross_validation() {
    let ties = [3.0, 1.0, 4.0, 1.0, 5.0, 9.0, 2.0, 6.0, 5.0, 3.0];
    let p = NanPolicy::Propagate;
    expect(
        &rankdata(&ties, RankMethod::Average, p).unwrap(),
        &[4.5, 1.5, 6.0, 1.5, 7.5, 10.0, 3.0, 9.0, 7.5, 4.5],
    );
    expect(
        &rankdata(&ties, RankMethod::Min, p).unwrap(),
        &[4.0, 1.0, 6.0, 1.0, 7.0, 10.0, 3.0, 9.0, 7.0, 4.0],
    );
    expect(
        &rankdata(&ties, RankMethod::Max, p).unwrap(),
        &[5.0, 2.0, 6.0, 2.0, 8.0, 10.0, 3.0, 9.0, 8.0, 5.0],
    );
    expect(
        &rankdata(&ties, RankMethod::Dense, p).unwrap(),
        &[3.0, 1.0, 4.0, 1.0, 5.0, 7.0, 2.0, 6.0, 5.0, 3.0],
    );
    expect(
        &rankdata(&ties, RankMethod::Ordinal, p).unwrap(),
        &[4.0, 1.0, 6.0, 2.0, 7.0, 10.0, 3.0, 9.0, 8.0, 5.0],
    );
    // Derived: Min and Max bracket Average, and Average is their midpoint.
    let avg = rankdata(&ties, RankMethod::Average, p).unwrap();
    let min = rankdata(&ties, RankMethod::Min, p).unwrap();
    let max = rankdata(&ties, RankMethod::Max, p).unwrap();
    for index in 0..ties.len() {
        assert!((avg[index] - 0.5 * (min[index] + max[index])).abs() <= 1e-12);
    }
    // Derived: Ordinal is a permutation of 1..=n.
    let mut ordinal = rankdata(&ties, RankMethod::Ordinal, p).unwrap();
    ordinal.sort_by(f64::total_cmp);
    let expected: Vec<f64> = (1..=10).map(f64::from).collect();
    assert_eq!(ordinal, expected);

    let nv = [0.0, 2.0, 3.0, NAN, -2.0, NAN, 2.0];
    for method in [
        RankMethod::Average,
        RankMethod::Min,
        RankMethod::Max,
        RankMethod::Dense,
        RankMethod::Ordinal,
    ] {
        let r = rankdata(&nv, method, NanPolicy::Propagate).unwrap();
        assert_eq!(r.len(), nv.len());
        assert!(r.iter().all(|value| value.is_nan()));
    }

    let omit = NanPolicy::Omit;
    expect(
        &rankdata(&nv, RankMethod::Average, omit).unwrap(),
        &[2.0, 3.5, 5.0, NAN, 1.0, NAN, 3.5],
    );
    expect(
        &rankdata(&nv, RankMethod::Min, omit).unwrap(),
        &[2.0, 3.0, 5.0, NAN, 1.0, NAN, 3.0],
    );
    expect(
        &rankdata(&nv, RankMethod::Max, omit).unwrap(),
        &[2.0, 4.0, 5.0, NAN, 1.0, NAN, 4.0],
    );
    expect(
        &rankdata(&nv, RankMethod::Dense, omit).unwrap(),
        &[2.0, 3.0, 4.0, NAN, 1.0, NAN, 3.0],
    );
    expect(
        &rankdata(&nv, RankMethod::Ordinal, omit).unwrap(),
        &[2.0, 3.0, 5.0, NAN, 1.0, NAN, 4.0],
    );
}

// Native: ties are decided by exact equality here, unlike computeRank.
#[test]
fn exact_equality_separates_near_ties() {
    let near = [1.0, 1.0 + 1e-12];
    // Two distinct values, so two distinct ranks.
    expect(
        &rankdata(&near, RankMethod::Average, NanPolicy::Propagate).unwrap(),
        &[1.0, 2.0],
    );
    // The other ranking in this crate calls the same pair a tie, because its
    // tolerance is relative and 1e-12 is far below 1e-7.
    let mut same = near;
    openms::math::statistic_functions::compute_rank(&mut same).unwrap();
    assert_eq!(same, [1.5, 1.5]);

    // Signed zeros compare equal, so they tie; and because the ordering is the
    // source's `<` rather than the IEEE-754 total order, Ordinal still ranks
    // them by input position instead of putting -0.0 first.
    expect(
        &rankdata(&[0.0, -0.0], RankMethod::Average, NanPolicy::Propagate).unwrap(),
        &[1.5, 1.5],
    );
    expect(
        &rankdata(&[0.0, -0.0], RankMethod::Ordinal, NanPolicy::Propagate).unwrap(),
        &[1.0, 2.0],
    );
    // Infinities sort to the ends and are not NaN, so no policy applies.
    expect(
        &rankdata(
            &[f64::INFINITY, 0.0, f64::NEG_INFINITY],
            RankMethod::Average,
            NanPolicy::Raise,
        )
        .unwrap(),
        &[3.0, 2.0, 1.0],
    );
}
