#!/usr/bin/env python3
# Copyright (c) 2002-present, OpenMS Inc.
# SPDX-License-Identifier: BSD-3-Clause
# $Maintainer: OpenMS Rust contributors $
"""Generate the `test` and `minimum-rust` jobs of the Rust workflow.

Their feature slices used to be `--test` lists kept by hand: 183 names across
the two jobs, and 154 of the 332 integration tests on no reduced-feature line of
the minimum-Rust job at all. A test that exercises a feature-gated path without
carrying the gate's `#[cfg]` breaks only under a reduced feature set, and the
repository has shipped that twice (f2bf2ed, b1b52f7) - each time in a test some
slice happened to list.

So the minimum-Rust job's slices are derived. Every integration test runs there
under each smallest feature set its crate-level `#![cfg(...)]` admits - `{}` for
a test with no gate, which is a bare `cargo test --no-default-features` - and
that is exactly the build in which a missing `#[cfg]` shows. What cannot be
derived from a gate stays written down in JOBS: a slice that reaches an
item-level gate (`--features mzml --test peak_type_estimator`), a dependency
feature (`rusqlite/extra_check`), the serial/parallel split. Each such name
must be one the derivation would not add by itself, so everything listed below
is a choice somebody made.

The generated jobs stay in `.github/workflows/rust.yml` with every cargo line
written out, because `~/.local/bin/openms-ci-sweep.sh` reads the lines it runs
out of that file. Each job is split into matrix legs that run in parallel; a
leg is a set of steps, and the sweep, which ignores `if:`, still runs every
line of every leg. `tools/ci_coverage.py --check` refuses the result if any
recorded (job, features, target) unit stopped running.

  python3 tools/ci_matrix.py --check   # gate: the committed jobs are what this generates
  python3 tools/ci_matrix.py --write   # regenerate them in place
"""

import argparse
import collections
import difflib
import sys

from ci_coverage import WORKFLOW, TestGates, cargo_features, parse_cargo, record, test_targets

BEGIN = "  # >>> generated by tools/ci_matrix.py from its JOBS - edit there, then run it with --write\n"
END = "  # <<< end of generated jobs\n"


class Raw:
    """A line written out whole: `cargo test --locked <args>`."""

    def __init__(self, leg, args):
        self.leg, self.args = leg, args


class Bare:
    """`cargo test --locked --no-default-features [--features F]`: every target cargo selects."""

    def __init__(self, leg, features=""):
        self.leg, self.features = leg, features


class Slice:
    """`--no-default-features [--features F]` over named tests; a deriving job adds its own."""

    def __init__(self, leg, features, tests=""):
        self.leg, self.features, self.tests = leg, features, tests.split()


class Job:
    def __init__(self, name, toolchain, legs, lines, derive=False, derived_leg=None):
        self.name, self.toolchain, self.legs, self.lines = name, toolchain, legs, lines
        self.derive, self.derived_leg = derive, derived_leg


JOBS = (
    Job(
        "test", "stable", ("all-features", "slices"),
        [
            Raw("all-features", "--all-features --all-targets"),
            Raw("all-features", "--all-features --doc"),
            Slice("slices", "sqlite", "sqlite_connector mzml_sqlite_swath_handler"),
            Slice("slices", "sqlite rusqlite/extra_check", "sqlite_connector mzml_sqlite_swath_handler"),
            Slice("slices", "sqmass", "mzml_sqlite_handler mzml_precursor_activation"),
            Slice("slices", "sqmass rusqlite/extra_check", "mzml_sqlite_handler mzml_precursor_activation"),
            Bare("slices"),
            Bare("slices", "idxml"),
            Slice("slices", "paramxml", "paramxml system_file"),
            Slice("slices", "mzml paramxml",
                  "topp_dta_extractor topp_mzml_splitter topp_map_normalizer topp_spectra_filter_window_mower "
                  "topp_baseline_filter topp_baseline_filter_edges topp_cli_lifecycle topp_peak_picker_hi_res "
                  "topp_threads"),
            Slice("slices", "mzml paramxml featurexml", "topp_file_info topp_feature_finder_centroided file_info_checks"),
            Slice("slices", "mzml paramxml parallel", "topp_threads topp_peak_picker_hi_res peak_picking_experiment"),
            Slice("slices", "mzml", "mzml_source_file_round_trip"),
            Slice("slices", "featurexml", "featurexml file_handler"),
            Slice("slices", "cv-mapping", "cv_mapping_file cv_mapping_values"),
            Slice("slices", "semantic-validation", "semantic_validator cv_mapping_file cv_mapping_values"),
            Slice("slices", "mzml-validation", "mzml_validator semantic_validator cv_mapping_file"),
            Slice("slices", "mzml-schema", "mzml_schema mzml_schema_offline"),
            Slice("slices", "consensusxml", "consensusxml file_handler"),
            Slice("slices", "consensusxml idxml", "file_info_a7"),
        ],
    ),
    Job(
        "minimum-rust", "1.85.0", ("all-features", "mzml-paramxml", "slices"),
        [
            Raw("all-features", "--all-features --all-targets"),
            Raw("all-features", "--all-features --doc"),
            Bare("slices"),
            Slice("slices", "sqlite"),
            Slice("slices", "sqlite rusqlite/extra_check", "sqlite_connector mzml_sqlite_swath_handler"),
            Slice("slices", "sqmass", "mzml_precursor_activation"),
            Slice("slices", "sqmass rusqlite/extra_check", "mzml_sqlite_handler mzml_precursor_activation"),
            Slice("slices", "featurexml", "file_handler"),
            Slice("slices", "cv-mapping", "cv_mapping_values"),
            Slice("slices", "semantic-validation", "cv_mapping_file cv_mapping_values"),
            Slice("slices", "mzml-validation", "cv_mapping_file semantic_validator"),
            Slice("slices", "mzml-schema"),
            Slice("slices", "consensusxml", "file_handler"),
            Slice("slices", "numpress", "numpress"),
            Slice("slices", "paramxml", "system_file"),
            Slice("slices", "mzml", "faims_helper im_data_converter numpress_coder peak_type_estimator record_metadata"),
            Slice("slices", "proforma-json"),
            Slice("slices", "idxml"),
            Slice("slices", "mzml featurexml", "file_handler_type_detection file_info"),
            Slice("slices", "consensusxml idxml", "file_info_a7"),
            Slice("mzml-paramxml", "mzml paramxml", "signal_to_noise"),
            Slice("mzml-paramxml", "mzml paramxml featurexml", "feature_finder_picked_seeds file_info_checks"),
            Slice("mzml-paramxml", "mzml paramxml parallel", "peak_picking_experiment topp_peak_picker_hi_res topp_threads"),
        ],
        derive=True, derived_leg="slices",
    ),
)


class SpecError(Exception):
    pass


def feature_key(features):
    return " ".join(sorted(features.split())) or "{}"


def derived(table, tests):
    """feature key -> the tests that run there under their smallest gate-admitted set."""
    wanted = collections.defaultdict(set)
    for name in tests:
        for smallest in TestGates(name).minimal_feature_sets(table):
            wanted[" ".join(sorted(smallest)) or "{}"].add(name)
    return wanted


def resolve(job, table, tests):
    """The job's lines as (leg, command) in order, with a deriving job's tests added."""
    known = set(tests)
    keyed = {}
    for line in job.lines:
        if line.leg not in job.legs:
            raise SpecError(f"{job.name}: leg {line.leg!r} is not one of {job.legs}")
        if isinstance(line, (Bare, Slice)):
            key = (type(line).__name__, feature_key(line.features))
            if key in keyed:
                raise SpecError(f"{job.name}: two {key[0]} lines for features {key[1]}; merge them")
            keyed[key] = line
            unknown = set(getattr(line, "tests", ())) - known
            if unknown:
                raise SpecError(f"{job.name}: no integration test named {sorted(unknown)}")
    shadowed = sorted(k for kind, k in keyed if kind == "Slice" and ("Bare", k) in keyed)
    if shadowed:
        raise SpecError(f"{job.name}: a bare line already runs every test under {shadowed}; drop the slice")
    added = collections.defaultdict(set)
    extra = []
    if job.derive:
        for key, names in sorted(derived(table, tests).items()):
            if ("Bare", key) in keyed:
                continue
            line = keyed.get(("Slice", key))
            if line is None:
                spelling = "" if key == "{}" else key
                line = Slice(job.derived_leg, spelling)
                keyed[("Slice", key)] = line
                extra.append(line)
            redundant = sorted(set(line.tests) & names)
            if redundant:
                raise SpecError(
                    f"{job.name}: {redundant} under {key!r} would be derived anyway; "
                    "list only what a gate cannot say"
                )
            added[id(line)] |= names
    out = []
    for line in list(job.lines) + extra:
        if isinstance(line, Raw):
            out.append((line.leg, f"cargo test --locked {line.args}"))
            continue
        command = "cargo test --locked --no-default-features"
        if line.features:
            spelled = line.features if " " not in line.features else f'"{line.features}"'
            command += f" --features {spelled}"
        if isinstance(line, Slice):
            names = sorted(set(line.tests) | added[id(line)])
            if not names:
                raise SpecError(f"{job.name}: slice {line.features!r} selects no test")
            command += "".join(f" --test {name}" for name in names)
        out.append((line.leg, command))
    empty = [leg for leg in job.legs if not any(leg == l for l, _ in out)]
    if empty:
        raise SpecError(f"{job.name}: leg(s) {empty} run nothing")
    return out


def render_job(job, table, tests):
    lines = resolve(job, table, tests)
    legs = ", ".join(job.legs)
    text = [
        f"  {job.name}:\n",
        "    runs-on: ubuntu-latest\n",
        "    strategy:\n",
        "      fail-fast: false\n",
        "      matrix:\n",
        f"        leg: [{legs}]\n",
        "    steps:\n",
        "      - uses: actions/checkout@v4\n",
        f"      - uses: dtolnay/rust-toolchain@{job.toolchain}\n",
        "      - uses: Swatinem/rust-cache@v2\n",
        "        with:\n",
        "          key: ${{ matrix.leg }}\n",
        "      - uses: ./.github/actions/setup-libxml\n",
    ]
    for leg, command in lines:
        parse_cargo(command)  # refuse anything the coverage tool cannot read
        text.append(f"      - if: matrix.leg == '{leg}'\n")
        text.append(f"        run: {command}\n")
    return "".join(text)


def render(table=None, tests=None):
    table = cargo_features() if table is None else table
    tests = test_targets() if tests is None else tests
    return BEGIN + "".join(render_job(job, table, tests) for job in JOBS) + END


def split(workflow_text):
    if workflow_text.count(BEGIN) != 1 or workflow_text.count(END) != 1:
        raise SpecError("the workflow must hold exactly one generated block between the markers")
    head, rest = workflow_text.split(BEGIN)
    body, tail = rest.split(END)
    return head, BEGIN + body + END, tail


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--check", action="store_true")
    group.add_argument("--write", action="store_true")
    parser.add_argument("--workflow", default=str(WORKFLOW))
    args = parser.parse_args(argv)
    try:
        with open(args.workflow) as handle:
            current = handle.read()
        head, committed, tail = split(current)
        generated = render()
    except SpecError as problem:
        print(f"ci_matrix: {problem}")
        return 2
    if args.write:
        if committed != generated:
            with open(args.workflow, "w") as handle:
                handle.write(head + generated + tail)
            print("Regenerated the test and minimum-rust jobs.")
        else:
            print("The generated jobs are already current.")
        # A new test adds units to every line that selects all tests; record
        # them now, and refuse - loudly - anything this run would drop.
        status, message = record(args.workflow)
        print(message)
        return status
    if committed != generated:
        print("The test and minimum-rust jobs are not what tools/ci_matrix.py generates.")
        print("Edit JOBS in tools/ci_matrix.py, not the workflow, and run it with --write.")
        sys.stdout.writelines(difflib.unified_diff(
            committed.splitlines(True), generated.splitlines(True), "committed", "generated"))
        return 1
    print("The generated jobs are current.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
