#!/usr/bin/env python3
# Copyright (c) 2002-present, OpenMS Inc.
# SPDX-License-Identifier: BSD-3-Clause
# $Maintainer: OpenMS Rust contributors $
"""Project the packaged source JSON into literal dependency-free Rust rows.

Only generation/checking is exposed. This is not a public runtime JSON provider.
"""
import argparse
import json
import math
from pathlib import Path
import struct

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "resources/monosaccharides"


def quoted(value):
    if not isinstance(value, str):
        raise ValueError("monosaccharide text must be a string")
    # Rust uses \u{...}, unlike JSON; the packaged scientific names need no escapes
    # beyond quotes/backslashes/control characters supported by both languages.
    if any(ord(c) < 32 for c in value):
        raise ValueError("control characters are outside the embedded data grammar")
    return json.dumps(value, ensure_ascii=False)


def project():
    raw = (DATA / "monosaccharides.json").read_bytes()
    if len(raw) > 1024 * 1024:
        raise ValueError("embedded monosaccharide source exceeds 1 MiB")
    rows = json.loads(raw)["monosaccharides"]
    if not isinstance(rows, dict) or len(rows) > 1024:
        raise ValueError("embedded monosaccharides must be an object of at most 1024 rows")
    result = ["// Generated by tools/generate_monosaccharides.py; do not edit.",
              "// Masses are the stored source literals, independent of formula.", "&["]
    for symbol, row in sorted(rows.items()):
        if "mass" not in row:  # Source skips missing-mass entries before aliases.
            continue
        mass = row["mass"]
        if isinstance(mass, bool) or not isinstance(mass, (float, int)) or not math.isfinite(mass):
            raise ValueError("mass must be a finite JSON number")
        synonyms = row.get("synonyms", [])
        if not isinstance(synonyms, list):  # Source ignores non-array synonyms.
            synonyms = []
        bits = struct.unpack(">Q", struct.pack(">d", mass))[0]
        result += ["    EmbeddedMonosaccharide {",
                   f"        symbol: {quoted(symbol)},",
                   f"        name: {quoted(row.get('name', symbol))},",
                   f"        mass: f64::from_bits(0x{bits:016x}),",
                   f"        formula: {quoted(row.get('formula', ''))},",
                   "        synonyms: &[" + ", ".join(map(quoted, synonyms)) + "],",
                   "    },"]
    return "\n".join(result + ["]", ""])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = DATA / "monosaccharides.rs"
    expected = project()
    if args.check:
        if output.read_text() != expected:
            raise SystemExit("monosaccharide projection differs; regenerate it")
        print("monosaccharide projection matches packaged JSON")
    else:
        output.write_text(expected)


if __name__ == "__main__":
    main()
