#!/usr/bin/env python3
# Copyright (c) 2002-present, OpenMS Inc.
# SPDX-License-Identifier: BSD-3-Clause
# $Maintainer: OpenMS Rust contributors $
"""Translate exact pinned cleavage expressions to native rules and independent test hashes.

Requires the bundled resources/enzymes/Enzymes.xml and rustfmt.
The Python regex engine is used only to derive golden checks, never by the library.
"""
import xml.etree.ElementTree as ET
import argparse
import pathlib
import json
import re
import itertools
import hashlib
import subprocess
root = pathlib.Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser(description='Regenerate pinned enzyme metadata and independent regex golden hashes.')
parser.add_argument('--check', action='store_true', help='verify without writing')
args = parser.parse_args()
source = root/'resources/enzymes/Enzymes.xml'
assert hashlib.sha256(source.read_bytes()).hexdigest() == '2f160f3ec32db6257cb4eee43fd594b48cb36398a17b7af21bbba76bc8b16995', 'Unexpected enzyme source revision'
variants = ['Trypsin','ArgC','ArgCP','AspN','AspNB','AspNAmbic','Chymotrypsin','ChymotrypsinP','CNBr','FormicAcid','LysC','LysN','LysCP','PepsinA','TrypChymo','TrypsinP','V8DE','V8E','LeukocyteElastase','ProlineEndopeptidase','GlutamylEndopeptidase','AlphaLyticProtease','Iodobenzoate','Iodosobenzoate','StaphylococcalProteaseD','ProlineEndopeptidaseHKR','GluCPlusP','PepsinAPlusP','CyanogenBromide','ClostripainP','ElastaseTrypsinChymotrypsin','NoCleavage','UnspecificCleavage']
records = ET.parse(source).getroot().find('NODE').findall('NODE')
assert len(records)==len(variants)==33
q=lambda s: json.dumps(s,ensure_ascii=False)
output=['// Copyright (c) 2002-present, OpenMS Inc.', '// SPDX-License-Identifier: BSD-3-Clause', '// $Maintainer: OpenMS Rust contributors $', '// Generated by tools/generate_enzymes.py; do not edit manually.', '// Derived from pinned 7c029e8 share/OpenMS/CHEMISTRY/Enzymes.xml.', '// Source SHA-256: '+hashlib.sha256(source.read_bytes()).hexdigest(), 'use super::{CleavageRule, DigestionEnzymeProtein};', '', '/// All enzyme entries in the pinned OpenMS registry, with compiled cleavage rules.', '#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, PartialOrd, Ord, Hash)]', 'pub enum Protease {']
for v in variants:
 if v=='Trypsin':output.append('    #[default]')
 output.append('    '+v+',')
output+=['}', '', 'impl Protease {', '    pub const ALL: [Self; 33] = [']+['        Self::'+v+',' for v in variants]+['    ];','}', '', 'pub(super) static ENZYMES: [DigestionEnzymeProtein; 33] = [']
goldens=['# Python re matching of exact pinned enzyme regex; FNV-1a64 of every A-Z context', '# Context order: all 2-residue strings at bond1, then all 3-residue strings at bond2.', '# name\tcleaving_context_count\tfnv1a64']
for variant,node in zip(variants,records):
 row={i.attrib['name']:i.attrib['value'] for i in node.findall('ITEM')}
 synonyms=sorted({i.attrib['value'] for n in node.findall('NODE') for i in n.findall('ITEM')})
 regex=row['RegEx']
 if regex=='()':
  rule='CleavageRule::Never'
 else:
  pattern=r'(?:\(\?<=((?:\[[A-Z-]+\]|[A-Z])+)\))?(?:\(\?=(\[[A-Z-]+\])\))?(?:\(\?!([A-Z])\))?'
  match=re.fullmatch(pattern,regex)
  assert match,regex
  left,right,forbidden=match.groups()
  sets=re.findall(r'\[([A-Z-]+)\]|([A-Z])', left or '')
  sets=[a or b for a,b in sets]
  assert len(sets)<=2
  prev=sets[-1] if sets else ''
  prev2=sets[0] if len(sets)==2 else ''
  prev=prev.replace('A-Z','ABCDEFGHIJKLMNOPQRSTUVWXYZ')
  right=right[1:-1] if right else ''
  rule='CleavageRule::Boundary { previous: b'+q(prev)+', previous_two: b'+q(prev2)+', next: b'+q(right)+', forbidden_next: b'+q(forbidden or '')+' }'
 output+=['    DigestionEnzymeProtein {','        protease: Protease::'+variant+',','        name: '+q(row['Name'])+',','        regex: '+q(regex)+',','        description: '+q(row.get('RegExDescription',''))+',','        synonyms: &['+', '.join(q(s) for s in synonyms)+'],','        n_term_gain: '+q(row.get('NTermGain',''))+',','        c_term_gain: '+q(row.get('CTermGain',''))+',','        psi_id: '+q(row.get('PSIID',''))+',','        xtandem_id: '+q(row.get('XTandemID',''))+',']
 for field,key in [('comet_id','CometID'),('msgf_id','MSGFID'),('omssa_id','OMSSAID')]:
  output.append('        '+field+': '+('Some('+row[key]+')' if key in row and row[key]!='-1' else 'None')+',')
 output+=['        rule: '+rule+',','    },']
 compiled=re.compile(regex)
 h=14695981039346656037; count=0
 for length in [2,3]:
  for chars in itertools.product('ABCDEFGHIJKLMNOPQRSTUVWXYZ', repeat=length):
   text=''.join(chars)
   cleaves=regex!='()' and compiled.match(text,length-1) is not None
   count+=cleaves
   h=((h^int(cleaves))*1099511628211)&((1<<64)-1)
 goldens.append(row['Name']+'\t'+str(count)+'\t'+format(h,'016x'))
output.append('];')
formatted = subprocess.run(['rustfmt', '--edition', '2024', '--emit', 'stdout'], input='\n'.join(output)+'\n', text=True, capture_output=True, check=True).stdout
files = {root/'src/chemistry/digestion/enzymes.rs': formatted, root/'tests/data/enzyme_cleavage_golden.tsv': '\n'.join(goldens)+'\n'}
for path, contents in files.items():
    if args.check:
        if path.read_text() != contents:
            raise ValueError(f'Generated data differs: {path}')
    else:
        path.write_text(contents)
print(f'{"Verified" if args.check else "Generated"} 33 enzymes and 602316 regex contexts')
