#!/usr/bin/env python3
# Copyright (c) 2002-present, OpenMS Inc.
# SPDX-License-Identifier: BSD-3-Clause
# $Maintainer: OpenMS Rust contributors $
"""Project the pinned fourteen RNA enzyme records; no runtime XML dependency."""
import argparse
import hashlib
import json
from pathlib import Path
import xml.etree.ElementTree as ET

root = Path(__file__).resolve().parent.parent
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
source = root / 'resources/enzymes/Enzymes_RNA.xml'
assert hashlib.sha256(source.read_bytes()).hexdigest() == '4c90a3630a1553ef7c75bae00f2731e2f5bb690f3ee9434d54cc3315a95fe899'
records = ET.parse(source).getroot().findall('./NODE/NODE')
assert len(records) == 14
fields = ['Name', 'RegExDescription', 'CutsAfter', 'CutsBefore', 'FivePrimeGain', 'ThreePrimeGain']
lines = ['// Copyright (c) 2002-present, OpenMS Inc.', '// SPDX-License-Identifier: BSD-3-Clause', '// $Maintainer: OpenMS Rust contributors $', '// Generated by tools/generate_rnases.py from pinned Enzymes_RNA.xml.', '&[']
for node in records:
    values = {item.attrib['name']: item.attrib['value'] for item in node.findall('ITEM')}
    assert set(values) <= set(fields), values
    lines.append('    (' + ', '.join(json.dumps(values.get(field, ''), ensure_ascii=False) for field in fields) + '),')
lines.append(']')
text = '\n'.join(lines) + '\n'
output = root / 'resources/enzymes/rna_enzymes.rs'
if args.check:
    assert output.read_text() == text, 'RNA enzyme projection differs'
else:
    output.write_text(text)
print(('Verified' if args.check else 'Generated') + '14 RNA enzyme records')
