#!/usr/bin/env python3
"""Project the two unchanged source FFM models to immutable binary64 Rust tables."""
from pathlib import Path
import argparse
import math
import struct

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "resources/metabolite_isotope_models"


def value(text):
    number = float(text)
    if not math.isfinite(number):
        raise ValueError("nonfinite model value")
    return number


def bits(number):
    return f"f64::from_bits(0x{struct.unpack('<Q', struct.pack('<d', number))[0]:016x})"


def project(noise):
    lines = (DATA / f"MetaboliteIsoModelNoised{noise}.svm").read_text().splitlines()
    start = lines.index("SV")
    fields = dict(line.split(" ", 1) for line in lines[:start])
    count = 548 if noise == 2 else 999
    assert fields["svm_type"] == "c_svc" and fields["kernel_type"] == "rbf"
    assert fields["nr_class"] == "2" and fields["label"] == "2 1"
    assert int(fields["total_sv"]) == count
    assert sum(map(int, fields["nr_sv"].split())) == count
    assert len(lines[start + 1:]) == count
    scale = [list(map(value, line.split())) for line in
             (DATA / f"MetaboliteIsoModelNoised{noise}.scale").read_text().splitlines()]
    assert len(scale) == 4 and all(len(pair) == 2 and pair[1] > 0 for pair in scale)
    gamma, rho = value(fields["gamma"]), value(fields["rho"])
    assert gamma > 0
    rows = []
    for line in lines[start + 1:]:
        row = line.split()
        assert len(row) == 5
        coefficient = value(row[0])
        pairs = [part.split(":") for part in row[1:]]
        assert [int(pair[0]) for pair in pairs] == [1, 2, 3, 4]
        features = [value(pair[1]) for pair in pairs]
        rows.append("        SupportVector { coefficient: " + bits(coefficient) +
                    ", features: [" + ", ".join(map(bits, features)) + "] },")
    return ("// Generated by tools/generate_metabo_isotope_models.py; do not edit.\n"
            "// Source OpenMS model resources, SPDX-License-Identifier: BSD-3-Clause\n"
            "ModelData {\n    gamma: " + bits(gamma) + ",\n    rho: " + bits(rho) +
            ",\n    centers: [" + ", ".join(bits(p[0]) for p in scale) +
            "],\n    scales: [" + ", ".join(bits(p[1]) for p in scale) +
            "],\n    support: &[\n" + "\n".join(rows) + "\n    ],\n}\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for noise in (2, 5):
        target = DATA / f"noise{noise}.rs"
        content = project(noise)
        if args.check:
            if target.read_text() != content:
                raise SystemExit(f"projection mismatch: {target}")
        else:
            target.write_text(content)
        print(f"{'checked' if args.check else 'generated'} noise{noise}: {548 if noise == 2 else 999} support vectors")


if __name__ == "__main__":
    main()
